### ISSUE TITLE
Provide Editor Notes

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#100]
Some basic notes on how to load the schema in an editor and play with it would be helpful for us to explore and expand the schema.

**Comment by rdb** [comment]
See https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings

**Comment by jag3773** [comment]
Note that for whatever reason I wasn't having success using the global settings.json but it worked when I put it in `.vscode/settings.json` in my scripture-burrito working directory.

**Comment by mvahowe** [comment]
I think this would be a good thing to include in the 0.2 documentation.

**Comment by jag3773** [comment]
@mvahowe I did stick it in the README, do we want it in the RTD site too?

**Comment by jag3773** [comment]
This information is in https://github.com/bible-technology/scripture-burrito#validation, should we link to it from the docs?  Seems like a section about "How to use" would be appropriate, but maybe not for 0.2.0.
