### ISSUE TITLE
Processing Model

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#101]

**Comment by mvahowe** [comment]
I need to do a lot more typing, but this is a more final version of the sketch I was waving around at our last meeting.
[state_changes.pdf](https://github.com/bible-technology/scripture-burrito/files/3989500/state_changes.pdf)

**Comment by mvahowe** [comment]
Here's some more typing, ripped from my private burrito store repo pending a discussion about where to put the 0.2 documentation:

[README.pdf](https://github.com/bible-technology/scripture-burrito/files/4013050/README.pdf)

**Comment by mvahowe** [comment]
Updated processing model
[README.pdf](https://github.com/bible-technology/scripture-burrito/files/4015466/README.pdf)

**Comment by jag3773** [comment]
Latest is at https://github.com/bible-technology/scripture-burrito-store-js/blob/master/build/doc_intro.md .
