### ISSUE TITLE
scopeOrRole is borderline unparseable

### ISSUE THREAD

**Issue by rdb** [bible-technology/scripture-burrito#103]
The ingredient definition has a scopeOrRole field that can be pretty much anything and the validation rules include a regular expression longer than 1400 characters ([see schema](https://github.com/bible-technology/scripture-burrito/blob/089378af8206fb5d387c172be9a01a3e50847e36/schema/ingredient.schema.json#L21-L49)). I’m a little unfamiliar with the meaning of this field, but perhaps we should split this up into an object structure that makes it easier to interpret?

**Comment by rdb** [comment]
bookScope also uses a custom language, although a significantly simpler one that I'm not as intimidated by:
```
    "bookScope": {
        "GEN": "1,2-3,4:4-6:7"
    }
```
It still requires a custom parser, so I'll add it here for consideration.

**Comment by mvahowe** [comment]
One point to consider is that the current format isn't just an arbitrary text format for users, it's what Paratext does, and, more importantly, what we have in USX:
```
<para style="s">John the Baptist's Message</para>
  <para style="r">(<ref loc="MAT 3:1-12">Matthew 3.1-12</ref>; <ref loc="MRK 1:1-8">Mark 1.1-8</ref>; <ref loc="LUK 3:1-18">Luke 3.1-18</ref>)</para>
```
In the current scheme, those references would be represented in metadata as
```
MAT 3:1-12;MRK 1:1-8;LUK 3:1-18
```
In other words, the current scheme is going to look very familiar to anyone processing USX. I believe that this is the internal format used by Paratext. In any case, there's no sane way to turn each reference into a hierarchy in XML, let alone in USFM. So, if we unpack references in the metadata JSON, we're introducing skew compared to the USX.

**Option A**
```
["MAT 3:1-12", "MRK 1:1-8", "LUK 3:1-18"]
```
This would arguably be closer to the USX than the current scheme, and this change would make the regex half the length.

**Option B**
```
[["MAT", "3:1-12"], ["MRK",  "1:1-8"], ["LUK", "3:1-18"]]
```
This allows for harvesting of (possibly duplicate) book names without string parsing and preserves reference order.

**Option C**
```
{"MAT": ["3:1-12"], "MRK":  ["1:1-8"], "LUK": ["3:1-18"]}
```
This avoids redundant book names at the expense of losing reference order.

**Option D**
```
{"MAT": [{"startChapter": "3", "startVerse": "1", "endVerse": 12"}, MRK":  [{startChapter": "1", "startVerse": "1", "endVerse": "8"}], "LUK": [{"startChapter": "3", "startVerse": "1", "endVerse": "18"}]
```
Something like this provides a completely explicit representation. It's also quite hard to read and seriously bloaty. (It could make a good internal representation for a processor though, and indeed I have code a lot like this in Nathanael.)

I suggest option C. What do others think?

**Comment by rdb** [comment]
I would be happy to compromise on option C.

**Comment by jag3773** [comment]
What do you think about a variation on C that preserve's reference order?

### Option E

```
[ {"MRK":  ["1:1-8"]}, {"LUK": ["3:1-18"]}, {"MRK":  ["5:6"]} ]
```

If this undesirable for some reason I'm OK with Option C also.

**Comment by mvahowe** [comment]
@jag3773 I think option E is essentially option B - in both cases you have a list of tuples.

Here and elsewhere we need to be very clear about whether order matters. If it does, all processors need to respect it. If it doesn't, no processor should rely on it. Any sentence about this including the words "some people" is a recipe for endless pain for everyone. (This also goes for the agencies conversation.)

In the case of scope, I don't think the order matters - we're basically specifying a subset of verses within a book. In the case of a printable set of references, the order may well matter.

Which seems like a good point to mention that the borderline unparsable format is what PT and DBL already use internally to represent machine-readable references within USX. Those references in USX are going to need processing whatever we do about the metadata. Also, we'd need something like the borderline unparsable format if we wanted to access arbitrary ranges of content via URLs, or indeed for semantic links to content. (No-one is going to love us if we come up with a linking format requiring nested JSON.) So I think we're going to be maintaining something like the borderline unparsable regex regardless. The question then is whether we want to maintain something else too.

**Comment by mvahowe** [comment]
For reference, here's an example of a reference in USX:
```
<para style="io1">Jesus' public ministry <char style="ior">(<ref loc="JHN 2:1-12:50">2.1–12.50</ref>)</char></para>
```

**Comment by rdb** [comment]
If that is what is established in the USX/USFM standard, then I won't oppose just going with it.  The Registry will probably not need to be able to parse the whole thing (but if it did, I'd suggest that we publish some npm library to parse scripture references).

I'll just leave the opinion here that I think separating out at least the books makes sense to me, which is why I did this for bookScope:
```json
"bookScope": {
    "GEN": "1-12",
    "EXO": "2-3"
}
```
This makes it a bit easier to extract a book list if that's all you're interested in, and it made it trivial to validate with JSON-Schema that no books occur here that are out-of-canon.  (I'm sure that'd still be possible with a bunch more ugly regexes, though.)

I think also separating out the ranges, as in C, makes sense.  But that's just my 2 eurocents ¯\\\_(ツ)\_/¯

**Comment by mvahowe** [comment]
Wait, we're worried about regex ugliness but ok with Javascript ;-)

The issue with the bookScope proposal is that we may not know the verses in a chapter (eg for all current DBL SL and audio entries). In the XML examples I believe I added a comment to the effect that bookScopes should be as short as possible, eg "GEN" not "GEN 1-50" or "GEN 1:1-32;2:1-..."

**Comment by jag3773** [comment]
We're still happy with option C :)

**Comment by mvahowe** [comment]
I went with option C :-)

I also forgot to make a PR, but the tests pass on develop.
