### ISSUE TITLE
Change rightsholder and rightsAdmin syntax

### ISSUE THREAD

**Issue by rdb** [bible-technology/scripture-burrito#109]
> > The rightsholders and rights administrator are now indices into the root agencies array.
> 
> Having thought about this some more, I think this is a step too far towards optimising the JSON as an internal data representation.
> 
> ```"rightsHolderAgencies": [0, 1]```
> 
> is hard to read but, more importantly, it's fragile. If the list of agencies is edited, and this indexing is not updated accordingly, we're screwed. All processors would need something like DB transactions to ensure that this didn't happen.
> 
> Part of the motivation for this is preserving order. But, in SB, the order here (and in general) does not have any semantics. If pre-SB processors do rely on order, I think that's a migration issue.
> 
> I think that a list of ids would do the job at least as well, with almost no bloat, ie
> 
> ```"rightsHolderAgencies": ["dbl::123", "agmt::123"]```

_Originally posted by @mvahowe in https://github.com/bible-technology/scripture-burrito/pull/95#issuecomment-562574983_

**Comment by rdb** [comment]
Maybe we should do this for contributors as well, and change the agencies list back to a dictionary?

**Comment by mvahowe** [comment]
I liked the agencies list as a dictionary.

**Comment by rdb** [comment]
One idea I had was something along the lines of this (ignore the exact locations or key names for now):
```json
"rightsHolders": ["dbl:123", "dbl:456", "dbl:789"]
"contributors": [
    {"id": "dbl:123", "management": true}
],
"agenciesInfo": {
    "dbl:123": {
        "name": "Some Bible Society"
    }
}
```
In the above example, the "agenciesInfo" basically contains static information fetched from the DBL about the organisations referenced.  Someone parsing "contributors", if they are unable to understand the organisation identifiers, would just need to do a dictionary lookup in "agencies".

A system like the Registry, or something else capable of knowing about agencies in another manner, would not need to store "agenciesInfo" at all since the Registry does not store this information in a denormalised manner like DBL does.

I don't really feel strongly about this either way but I do currently feel inclined towards keeping the denormalised and the normalised data separate.

**Comment by FoolRunning** [comment]
I'm probably missing something, but how would the Paratext Registry know that the contributor in the SB:
```
"contributors": [
    {"id": "blb23:a123bc", "management": true}
]
```
corresponds to the entry in the Registry:
```
"orgs": [
    {"id": "2aa9bea8bfd400c04363b3e3ea51badefc86259a", "name": "American Bible Society", "abbr": "ABS", ... }
]
```

**Comment by rdb** [comment]
@FoolRunning It wouldn't, and in fact none of the proposals on the table would allow this.

**Comment by mvahowe** [comment]
@rdb I disagree, that's what idServers do for us.

**Comment by rdb** [comment]
I don't think idServers help the Registry do that, but regardless, nothing about any of the proposed rightsholder or rightsAdmin syntaxes alter the way idServers works, so all this seems off-topic to the matter of our rightsholder or rightsAdmin syntax.

**Comment by jag3773** [comment]
We decided @rdb 's idea above is what we'll use.  Processors *should* maintain order.

**Comment by mvahowe** [comment]
If we combine the rightsHolders and contributors, I'm not sure we need to separate the agencies from the agenciesInfo.

So, concretely:
```
"agencies" : [
    {
        id: "dbl:123",
        "agencyInfo": {
            "isRightsHolder": true,
            "name": "Some Bible Society"
        }
    },
    {
        id: "dbl:456",
        "agencyInfo": {
            "isRightsHolder": false,
            "name": "Some Other Bible Society"
        }
    }
]

```
where isRightsHolder is assumed to be false if absent.

(I still think that this data is crying out to be stored in a dictionary with the id as a key, where the keys are the ids and the values are the denormalized data relating to that key. But, if you want order to matter in JSON, you can't do that, because JSON has no notion of "document order".)

Any objections?

**Comment by rdb** [comment]
Surely isRightsHolder should be outside the agencyInfo here?  It's not part of the organisation profile, but part of the binding between the organisation and the burrito.

One thing to note is that the Registry and DBL have a special arrangement regarding the immutability of rightsholders once an entry gets into the DBL, that does not apply to contributors.  We would have to revisit this arrangement if we merge the two.

**Comment by mvahowe** [comment]
@rdb Ok, and there's no contributor flags in the last example, so maybe
```
"agencies" : [
    {
        "id": "dbl:123",
        "roles": {
            "isRightsHolder": true,
            "contributesFinance": true,
            "contributesQA": false
        },
        "agencyInfo": {
            "name": "Some Bible Society", # SHOULD BE 1 OR MORE BCP47-QUALIFIED NAMES
        }
    },
    {
        "id": "dbl:456",
        "roles": {
            "contributesQA": true,
        }
        "agencyInfo": {
            "name": "Some Other Bible Society"
        }
    }
]
```
I hope this isn't going to come as a shock, but DBL ends up hacking immutable rightsHolders quite a lot.

**Comment by jag3773** [comment]
Modify roles to be an array :)

**Comment by mvahowe** [comment]
So
```
"agencies" : [
    {
        "id": "dbl:123",
        "roles": ["rightsHolder", "finance", "qa"],
        "agencyInfo": {
            "name": {"en": "Some Bible Society"}
        }
    },
    {
        "id": "dbl:456",
        "roles": ["qa"],
        "agencyInfo": {
            "name": {"en": "Some Other Bible Society"}
        }
    }
]
```

**Comment by jag3773** [comment]
Looks good to me
