### ISSUE TITLE
Use case/challenge - vc diff across two idServers

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#117]
1. - User creates new project in PT, and makes 4 commits
2. - User exports project to uW and makes another 4 commits
3. - User exports project to PT and makes another 4 commits
4. - User wishes to compare commits 1 and 6
5. - User wishes to compare commits 6 and 10

**What do steps 4 and 5 look like in terms of vc commands?**

(To make it artificially easy, let's pretend that PTX and uW use the same vc system.)

**Comment by mvahowe** [comment]
My point is that we keep saying that "servers retain history" but, as soon as a project moves between servers, it becomes very hard to reason about that history, unless the burritos themselves contain some metadata to facilitate this. So, eg, PT could potentially grab commit 6 from uW, but to do this it needs to be able to walk back through the basedOn links. Without that, for PT, the uW period of the project is like a night out with too much alcohol - something happened but we have no idea what.

**Comment by mvahowe** [comment]
To put it another way, how would we produce the history of an ingredient (names and dates) for a burrito that has moved between idServers? So something like this, from github? This seems like quite basic functionality if we want interoperability to be a realistic option.

I think we can do all this from the metadata (assuming the metadata is available). But without some help from the metadata, I don't think it's possible without introspecting two vc systems which may not even be compatible with each other.
![git_history](https://user-images.githubusercontent.com/1576594/72615263-98a11e80-3934-11ea-8d56-6107b7bce400.png)

**Comment by jag3773** [comment]
With the basedOn field and an API that encapsulates different idServer's history mechanisms, a client could request the history of a project and reconstruct a combined history of the burrito.

**Comment by mvahowe** [comment]
I think we had this conversation and there were no action points so I'm going to close this.
