### ISSUE TITLE
custom.sty in a textTranslation flavor

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#134]
Related to #52 

[custom_sty.txt](https://github.com/bible-technology/scripture-burrito/files/4235377/custom_sty.txt)

This file is proposed for inclusion in the textTranslation flavor.

The content seems useful. I'd prefer to not express this kind of information in tortured USFM. (We don't want being able to work with invalid USFM to be a requirement of using SB.)

 However, if everyone is happy with the content, maybe we could go with the current format for 0.2 and agree to come up with a better format before 1.0?

**Comment by FoolRunning** [comment]
**custom.sty** is basically modifications to the USFM specification. I think we need to ask ourselves if we want to support that at all. I know we probably don't care about the text formatting (color, size, etc.) in a SB.

**Comment by mvahowe** [comment]
@FoolRunning One of my earlier false good ideas at YouVersion was using this file to control formatting, resulting in purple headings.

Dropping files is definitely the easy option. Can you ask if anyone on the PT side has an issue with this?

**Comment by jag3773** [comment]
Agreed to drop custom.sty.
