### ISSUE TITLE
ldml.xml in textTranslation flavor

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#135]
Related to #52 

[ldml-xml.txt](https://github.com/bible-technology/scripture-burrito/files/4235419/ldml-xml.txt)

There's a proposal to include this in the textTranslation flavor.

This is not my field, but it's in XML and is relatively self-documenting. I'd like to know if there's a schema for this XML vocabulary. Other than that, this looks good to go to me.

**Comment by rdb** [comment]
Possibly worth considering:
http://cldr.unicode.org/index/cldr-spec/json

**Comment by FoolRunning** [comment]
Probably worth noting is that LDML is part of the [Unicode specification for locale data](http://unicode.org/reports/tr35/).

**Comment by mvahowe** [comment]
@FoolRunning What would migration to this Unicode standard look like?

**Comment by FoolRunning** [comment]
For DBL and Paratext, it should be very simple since I think LDML files have always been required by DBL since Paratext started producing entries for it, and they have been required by Paratext since 8.0.

For other applications, it might be more complicated as they would have to create the LDML parser, etc.

**Comment by mvahowe** [comment]
Sounds to me like we have a proposal, which is to stick with what PT/DBL do already.

**Comment by jag3773** [comment]
To be clear, is the proposal to use the CLDR JSON format or the LDML XML format?

**Comment by jag3773** [comment]
Use the LDML XML but it won't be required.

**Comment by jtauber** [comment]
What are the acceptance criteria here? Just being able to ship an LDML file as an ingredient? Do we need to call it out in the metadata.json (I would think so as there are otherwise no assumptions about filenaming among the ingredients).

**Comment by jag3773** [comment]
Yes, we need to define it in the metadata.json and point to the actual file in the ingredients list.

**Comment by jtauber** [comment]
Okay there's two ways we can do this:

1) add a new flavor-specific property
2) use `role` on the ingredient

I was originally working on 1) but 2) might be easier.

As far as I can tell, there are no flavour-specific properties pointing to ingredients. Any calling out of specific ingredients for a specific purpose seems to be currently done through `role`.

**Comment by jag3773** [comment]
Option 2 is preferable here.
