### ISSUE TITLE
Paratext Settings file in textTranslation flavor

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#136]
Related to #52 

[Settings-xml.txt](https://github.com/bible-technology/scripture-burrito/files/4235455/Settings-xml.txt)

Including this seems problematic to me for 3 reasons:

- A lot of the content is clearly vendor-specific (or, at the very least, we'd need to document the semantics of each field for another vendor to edit anything safely)
- Some of the content overlaps with SB metadata. I don't think we want to store the same information in multiple places.
- In a "project leaves and re-enters PTX" use case, the merge process seems complex to me, especially if we don't know whether or not any of the information in this file has been maintained while outside of PTX

The easy (to specify) solution would be to have a place for any processor to dump whatever it likes, but I'd like to avoid doing that for as long as possible. (If we start down that route now I don't think we'll ever achieve interoperability on any meaningful level.) I think that a better solution might involve several of

- storing information such as copyright in existing SB metadata fields
- reconnecting with PT UI-type settings when the project re-enters PTX
- moving some of this information to the Registry
- coming up with ways to specify some of this information that could be used by multiple vendors in a portable way

This feels to me like a conversation that could easily go open-ended on us, so we may need to tackle the easiest use cases first.

@rdb How does any/all this look from the perspective of the Registry?

**Comment by rdb** [comment]
This looks like a big grab bag of Paratext-specific settings, project metadata, flavor details, system identifiers, book names, styling… much of this is already represented in other parts of the metadata.

I think we want to take this apart and figure out which of these Paratext needs for resources, and make sure we account for those in the metadata.

If Paratext really needs all of this, we might consider adding in an extension mechanism where Paratext-specific stuff could live, but obviously we would ideally avoid that.

**Comment by mvahowe** [comment]
@rdb Regardless of whether we want a way to store PT-specific stuff, I have a real question about how useful this would be to PT. If, say, a project goes off to uW for a year, and in the meantime the project is updated in PT, and then PT wants to merge the uW SB, which settings will it preserve? The ones from PT? In that case, why store the SB copy at all? The ones from SB? Even if uW has never updated them?

**Comment by rdb** [comment]
Yes, you're right.  It would be preferable not to have PT-specific settings in there.

I have sorted the list in the above .xml file into things that PT isn't using, things that appear to already be included in the metadata spec, things that appear to not need preservation (eg. PT UI state), and a remainder that needs to be sorted out further.

We need someone who knows PT to go through the last category and sort it out further into settings that Paratext needs in order to be able to read the resource, and settings that are only needed for editing and checking (which don't need to be present in PT resource burritos).  @FoolRunning, could you help with this?

<details><summary>Unused by PT or deprecated in PT</summary>
<p>

```xml
<AutoKeyboardSwitching>T</AutoKeyboardSwitching>
<WordlistRefreshBooksPresent>111111111111111111111111111111111111111111111111111111111111111111111111111111001110000000000000000000000000000000000000000</WordlistRefreshBooksPresent>
<NeedsEnglishLanguageFix>No</NeedsEnglishLanguageFix>
<NeedsPortugueseLanguageFix>No</NeedsPortugueseLanguageFix>
<CrossRefOriginHasChapter>True</CrossRefOriginHasChapter>
<BookAbbreviations>Gen|Ex|Lev|Num|Deut|Josh|Judg|Ruth|1 Sam|2 Sam|1 Kgs|2 Kgs|1 Chr|2 Chr|Ezra|Neh|Esth|Job|Ps|Prov|Ecc|Song|Is|Jer|Lam|Ezek|Dan|Hos|Joel|Amos|Obad|Jon|Mic|Nah|Hab|Zeph|Hag|Zech|Mal|Mt|Mk|Lk|Jn|Acts|Rom|1 Cor|2 Cor|Gal|Eph|Phil|Col|1 Thes|2 Thes|1 Tim|2 Tim|Tit|Phlm|Heb|Jas|1 Pet|2 Pet|1 Jn|2 Jn|3 Jn|Jude|Rev|Tob|Jdt|Gk Est|Wis|Sir|Bar|Let Jer|S of 3 Y|Sus|Bel|1 Macc|2 Macc|||1 Esd|2 Esd|Man||||||||||||||||||||||||||||||||||||||||</BookAbbreviations>
<ParallelRefBookNames>Genesis|Exodus|Leviticus|Numbers|Deuteronomy|Joshua|Judges|Ruth|1 Samuel|2 Samuel|1 Kings|2 Kings|1 Chronicles|2 Chronicles|Ezra|Nehemiah|Esther (Hebrew)|Job|Psalms|Proverbs|Ecclesiastes|Song of Songs|Isaiah|Jeremiah|Lamentations|Ezekiel|Daniel (Hebrew)|Hosea|Joel|Amos|Obadiah|Jonah|Micah|Nahum|Habakkuk|Zephaniah|Haggai|Zechariah|Malachi|Matthew|Mark|Luke|John|Acts|Romans|1 Corinthians|2 Corinthians|Galatians|Ephesians|Philippians|Colossians|1 Thessalonians|2 Thessalonians|1 Timothy|2 Timothy|Titus|Philemon|Hebrews|James|1 Peter|2 Peter|1 John|2 John|3 John|Jude|Revelation|Tobit|Judith|Esther Greek|Wisdom of Solomon|Sirach (Ecclesiasticus)|Baruch|Letter of Jeremiah|Song of 3 Young Men|Susanna|Bel and the Dragon|1 Maccabees|2 Maccabees|3 Maccabees|4 Maccabees|1 Esdras (Greek)|2 Esdras (Latin)|Prayer of Manasseh|Psalm 151|Odes|Psalms of Solomon|Joshua A. *obsolete*|Judges B. *obsolete*|Tobit S. *obsolete*|Susanna Th. *obsolete*|Daniel Th. *obsolete*|Bel Th. *obsolete*|||||||||||3 Ezra *obsolete*|Apocalypse of Ezra|5 Ezra (Latin Prologue)|6 Ezra (Latin Epilogue)||||||Daniel Greek|Psalms 152-155|2 Baruch (Apocalypse)|Letter of Baruch|Jubilees|Enoch|1 Meqabyan|2 Meqabyan|3 Meqabyan|Reproof (Proverbs 25-31)|4 Baruch (Rest of Baruch)|Laodiceans</ParallelRefBookNames>
<TextEntryFontSizeAdjustment>0</TextEntryFontSizeAdjustment>
<PaOriginalStylesheetName />
<Naming PrePart="" PostPart="GNTUK.SFM" BookNameForm="41MAT" />
Anything beginning with "pp"
```

</p>
</details>

<details><summary>Possibly already included in SB metadata or obsoleted by SB</summary>
<p>

```xml
<MinParatextVersion>8.0.63.1</MinParatextVersion>
<Guid>de08848bef5aa2866c8932e6ce5541206eda3da9</Guid>
<Copyright>&lt;p&gt;Good News Translation® with Deuterocanonicals/Apocrypha (Today’s English Version, Second Edition) © 1992 American Bible Society. All rights reserved.&lt;/p&gt;&lt;p&gt;Anglicisation © The British and Foreign Bible Society 1976, 1994, 2004&lt;/p&gt;&lt;p&gt;The copyright for the derivative work of Anglicisation pertains only to the text within the Good News Translation (GNT) that British and Foreign Bible Society adapted for British literary usage, consistent with Section 103(b) of the United States Copyright Act, 17 U.S.C. § 103(b).&lt;/p&gt;&lt;p&gt;Bible text from the Good News Translation (GNT) is not to be reproduced in copies or otherwise by any means except as permitted in writing by American Bible Society, 101 North Independence Mall East, Floor 8, Philadelphia, PA 19106-2155 (www.americanbible.org).&lt;/p&gt;&lt;p&gt;All rights reserved. No part of this publication may be reproduced or transmitted in any form or by any means, electronic or mechanical, including photocopy, recording or any information storage or retrieval system, without permission in writing from the publisher.&lt;/p&gt;</Copyright>
<LeftToRight>T</LeftToRight>
<FullName>English-UK: Good News Translation 1994</FullName>
<Language>English</Language>
<LanguageIsoCode>en:::</LanguageIsoCode>
<TMSId>11466f4b-0ee7-46e4-99d6-64097e22f4da</TMSId>
<GBCId>53ac24395117ad56de2354a8</GBCId>
<ParatextRegistryId>s89xzMTEo4Tr4rQsB</ParatextRegistryId>
<Visibility>Public</Visibility>
<DateArchived>2011-12-12T00:00:00</DateArchived>
<Book_XYZ>Book Name</Book_XYZ>
<Encoding>65001</Encoding>
<BooksPresent>111111111111111111111111111111111111111111111111111111111111111111111111111111001110000000001000001100000001100100000000000</BooksPresent>
<AssociatedAdditionsProject />
<AssociatedLexicalProject />
```

</p>
</details>

<details><summary>Possible UI settings in Paratext that do not need to be preserved in SB</summary>
<p>

```xml
<AdvancedView>False</AdvancedView>
<CharacterAdvancedView>True</CharacterAdvancedView>
<MarkerAdvancedView>False</MarkerAdvancedView>
<SentenceFinalAdvancedView>False</SentenceFinalAdvancedView>
<InitialImportBooksDirectory>C:\My Paratext Projects\GNTUK</InitialImportBooksDirectory>
```

</p>
</details>

<details><summary>To be decided</summary>
<p>

```xml
<Editable>T</Editable>
<DefaultFont>Cambria</DefaultFont>
<DefaultFontSize>16</DefaultFontSize>
<FileNameForm>41MAT</FileNameForm>
<FileNamePostPart>GNTUK.SFM</FileNamePostPart>
<Name>GNTUK</Name>
<StyleSheet>usfm.sty</StyleSheet>
<Versification>4</Versification>
<FileNameBookNameForm>41MAT</FileNameBookNameForm>
<Pairs>(/) [/] {/}</Pairs>
<ClosedByParagraph>No</ClosedByParagraph>
<PoeticStyles>ib iq iq1 iq2 iq3 q q1 q2 q3 q4 qc qr qs qa qac qm qm1 qm2 qm3 b</PoeticStyles>
<IntroductionOutlineStyles>io io1 io2 io3 io4</IntroductionOutlineStyles>
<ValidCharacters>  G E N S I T h e F i r s t B o k f M c a l d n R O D U C m “ g ” . b u v , w ' y p : ( 1 ) H A — 2 J 5 0 W j 3 – 4 6 9 7 8 … ; L P x - Y ‘ ’ ? z q Z K ! V Q X [ ] = -'´—' ‌ ‍ é ë ö ü © / % # * + \ ´ ê ô É Ë Ü ē Ē Ö § ®</ValidCharacters>
<InterlinearModelText>BFC97N</InterlinearModelText>
<InterlinearRelatedLanguages.MPGr2>True</InterlinearRelatedLanguages.MPGr2>
<InterlinearExportText.MPGr2>MPGr2</InterlinearExportText.MPGr2>
<InterlinearExportOnApprove.MPGr2>True</InterlinearExportOnApprove.MPGr2>
<InterlinearRelatedLanguages.BFC97N>False</InterlinearRelatedLanguages.BFC97N>
<InterlinearExportText.BFC97N>HTP1</InterlinearExportText.BFC97N>
<InterlinearExportOnApprove.BFC97N>False</InterlinearExportOnApprove.BFC97N>
<Quotes>“ ”</Quotes>
<InnerQuotes>‘ ’</InnerQuotes>
<InnerInnerQuotes>“ ”</InnerInnerQuotes>
<ContinueQuotes>Yes</ContinueQuotes>
<VerboseQuotes>No</VerboseQuotes>
<ContinueAt>p b/q1 c/q1 pi s1/q1</ContinueAt>
<ValidPunctuation>_“ ”_ ._ ,_ ' :_ _( )_ …_ ;_ _—_ - _‘ ’_ ?_ !_ '_ _… ) … – _…_ _?_ _[ ]_ — _(_ _=_ _”_ . _’_ _[_ %_ _©_ / _#_ ´ ‌ ‍ _/ _*_ _* _/_ ( _§_ ®_</ValidPunctuation>
<ValidUncapitalizedStyles>ft fq fk xo io2 q2 li tr tcr1 nb q1 it nd tc1 tc2 bk fr tcr2 wj bd p mt1 t k pc zpa-d sc fqa em xtSeeAlso im</ValidUncapitalizedStyles>
<SegmentOrder>a b c</SegmentOrder>
<RangeIndicator>–</RangeIndicator>
<SequenceIndicator>, </SequenceIndicator>
<ChapterVerseSeparator>.</ChapterVerseSeparator>
<ChapterRangeSeparator>—</ChapterRangeSeparator>
<ChapterNumberSeparator>; </ChapterNumberSeparator>
<BookSequenceSeparator>; </BookSequenceSeparator>
<RepeatableWords>had Job Ezra Joel Jude 3 Ruth D 2 Acts 1 Amos</RepeatableWords>
<ValidSentenceFinalPunctCapitalization>! ’ : ] . ? , ; … ' ) ” %</ValidSentenceFinalPunctCapitalization>
<ContinueInnerQuotes>Yes</ContinueInnerQuotes>
<CrossReferenceSettingsHaveBeenReviewed>T</CrossReferenceSettingsHaveBeenReviewed>
<BookSourceForMarkerXt>Abbreviation</BookSourceForMarkerXt>
<BookSourceForMarkerR>Abbreviation</BookSourceForMarkerR>
<ReferenceExtraMaterial> (Title)| (LXX)</ReferenceExtraMaterial>
<SortByCount>No</SortByCount>
<Err_CountSFMsHeading>Marker,  Count,  Name (preceded by)</Err_CountSFMsHeading>
<TranslationInfo>Standard::</TranslationInfo>
<BiblicalTermsListSetting>Major::BiblicalTerms.xml</BiblicalTermsListSetting>
<RefsMustMatchVerseSegments>True</RefsMustMatchVerseSegments>
<SegmentsMustHaveFinalPunctuation>False</SegmentsMustHaveFinalPunctuation>
<NoSpaceBetweenBookAndChapter>False</NoSpaceBetweenBookAndChapter>
<MatchedPairingCharacters>( ) [</MatchedPairingCharacters>
<ValidMixedCapitalization>FrutigerNext HarperCollinsPublishers</ValidMixedCapitalization>
<NumberDecimalPoint>.</NumberDecimalPoint>
<NumberThousandsSeparator>,</NumberThousandsSeparator>
<NumberOrdinals>s st nd rd th</NumberOrdinals>
<NumberInitialPunctuation>(</NumberInitialPunctuation>
<NumberFinalPunctuation>),.;</NumberFinalPunctuation>
<NumberMedialPunctuation>—-</NumberMedialPunctuation>
<NumberOrdinalType>suffix</NumberOrdinalType>
<NumberSettingsHaveBeenReviewed>T</NumberSettingsHaveBeenReviewed>
<AllowReadAccess>F</AllowReadAccess>
<AllowSharingWithSLDR>F</AllowSharingWithSLDR>
<ValidParagraphFinalPunctuationItems>p tr li im ip q2 ie q1</ValidParagraphFinalPunctuationItems>
<HindiUrduNumberGrouping>F</HindiUrduNumberGrouping>
<FileName>RC_A.lcf</FileName>
<ShowReferences>Yes</ShowReferences>
<ShowVerseNumbers>No</ShowVerseNumbers>
<OriginRangeOption>MatchVerseExactly</OriginRangeOption>
<Continuer>“</Continuer>
<InnerContinuer>‘</InnerContinuer>
<InnerInnerContinuer>“</InnerInnerContinuer>
<QuoteClosesAllQuoteLevels>No</QuoteClosesAllQuoteLevels>
<FileNamePrePart />
<GBCSummary>English(eng), Good News Bible UK (Interconfessional Edition with Deuterocanonical books/Apocrypha) 2004, United Kingdom, Bible with Deuterocanon, 1992-10-01, Published, UBS, GNTUK, dbl: matches, tms</GBCSummary>
<ReferenceFinalPunctuation />
<EncodingConverter />
<FontFeatures />
<HtmlLanguage />
<InvalidCharacters />
<InvalidPunctuation />
<BibleModuleAssociations>XXA:Lives of the Prophets (IBS).txt</BibleModuleAssociations>
<MatchBasedOnStems>F</MatchBasedOnStems>
<InvalidParagraphFinalPunctuationItems />
<InvalidUncapitalizedStyles />
<InvalidSentenceFinalPunctCapitalization />
```

</p>
</details>

**Comment by FoolRunning** [comment]
> Follow-up question: what are "cms" files and do options declared in cms files need to be preserved for PT resource burritos?

CMS files are basically custom Python scripts that are run inside of Paratext (I have no idea what CMS stands for - it was before my time). There is no reason to keep those settings in a SB.

> @FoolRunning, could you help with this?

The lists were so long, I thought I'd just post the list of things that Paratext needs:
* **BooksPresent**: List of books that are present in the project (handled by SB)   
* **Versification**: Versification used by the project (handled by SB - see #49)
* **LanguageIsoCode**: Language used by the project (handled by SB)
* **Language**: Language name (handled by SB)
* **FullName**: Full name of the project (handled by SB)
* **Name**: Short name/abbreviation of the project (handled by SB)
* **Guid**: The project ID (handled by SB)
* **Copyright**: Copyright information (handled by SB)
* **UsfmVersion**: USFM version used by the project (handled by SB)
* **FileNameBookNameForm**, **FileNamePrePart**, **FileNamePostPart**: Tells Paratext how to find a file for a particular book (should be handled by SB by describing which files correspond to which book)
* **Encoding**: Encoding of the text of the project (might be handled by SB - see #137)
* **TranslationInfo**: Basically the type of project (not completely handled by SB - see #93)
* **NormalizationForm**: Unicode normalization applied to the text (not handled by SB)

**Comment by rdb** [comment]
Well, that's certainly a lot less than I was fearing.  Thank you!  Looks like we've already either handled most of these or already have open issues for them.  We should create an issue to consider the Unicode normalization question.

I've been told that CMS stands for "Checking Menu Specification".

**Comment by FoolRunning** [comment]
I forgot to note that the things that @rdb categorized as "apparent checking options" would be nice to include in resources (see #52). This includes some of the checking settings that are in the "to be decided" section. So the list of "would be nice" would become:
**Pairs**, **ClosedByParagraph**, **ValidCharacters**, **Quotes**, **InnerQuotes**, **InnerInnerQuotes**, **ContinueQuotes**, **ContinueAt**, **ValidPunctuation**, **ValidUncapitalizedStyles**, **SegmentOrder**, **RangeIndicator**, **SequenceIndicator**, **RepeatableWords**, **ValidSentenceFinalPunctCapitalization**, **ContinueInnerQuotes**, **RefsMustMatchVerseSegments**, **SegmentsMustHaveFinalPunctuation**, **NoSpaceBetweenBookAndChapter**, **MatchedPairingCharacters**, **ValidMixedCapitalization**, **OriginRangeOption**, **ChapterVerseSeparator**, **ChapterRangeSeparator**, **ChapterNumberSeparator**, **BookSequenceSeparator**, **BookSourceForMarkerXt**, **BookSourceForMarkerR**, **ReferenceExtraMaterial**, **BiblicalTermsListSetting**, **NumberDecimalPoint**, **NumberThousandsSeparator**, **NumberOrdinals**, **NumberInitialPunctuation**, **NumberFinalPunctuation**, **NumberMedialPunctuation**, **NumberOrdinalType**, **ValidParagraphFinalPunctuationItems**, **HindiUrduNumberGrouping**, **Continuer**, **InnerContinuer**, **InnerInnerContinuer**, **QuoteClosesAllQuoteLevels**, **ReferenceFinalPunctuation**, **InvalidCharacters**, **InvalidPunctuation**, **MatchBasedOnStems**, **InvalidParagraphFinalPunctuationItems**, **InvalidUncapitalizedStyles**, **InvalidSentenceFinalPunctCapitalization**.

It's a long list and would probably be Paratext-specific, so we probably want to wait for custom settings. :)

**Comment by rdb** [comment]
@FoolRunning Help me understand why these settings are useful—do people typically need to run checks on downloaded resources?

**Comment by mvahowe** [comment]
@FoolRunning Some background I picked up from @klassenjm earlier today:

> You're looking _____ (somewhere, I'm not sure) and finding references to the cms folder. Perhaps you are looking in a project settings file? These used to be called <shortName>.ssf. I think it's projectSettings.xml now, or something like that. Perhaps you have found references to the cms folder -- because Paratext may have saved the last known user's configuration for running some of those scripture checks. Those checks were developed in the Paratext 6 era, and continued in Paratext 7, although a new way of many types of checking developed in PT 7 and 8 etc, based on "inventories". The cms folder contains specifications for checks. It let the dev team extend the Checking menu with new checks or utilities. A user could do this to by adding a cms file and writing a script. You could write a script in Python, Perl, or CC (Consistent Changes - an OLD SIL invented language for search / replace). Paratext provided a ScriptureObject interface which you could access via Python in order to get project information and content. All of the stuff in the CMS folder is one of these. I've written many little utilities to help a project. For example - I wrote one to 'devocalize' an Arabic text (allowing the project to maintain one master, but remove un-critical vowels when publishing). Paratext shipped with a standard set of checking tools. Before Publishing Assistant, there was a tool in there to "Export InDesign Tagged Text" or "Export Ventura Tagged Text".

**Comment by FoolRunning** [comment]
> Help me understand why these settings are useful—do people typically need to run checks on downloaded resources?

Yes, that is exactly what they do. I don't completely understand why, but Phil Leckrone said:

> Very often when I'm checking a text I want to compare it to the information in a resource. Having the checking information of a resource available is extremely helpful. Inventories I can find but rules as in quotations or numbers can't be looked up

So, it's entirely possible that not all of the settings I listed are useful, but they all related to checking so I included them. If we get to the point where we want to start including them, we should clarify exactly which ones are helpful.

**Comment by mvahowe** [comment]
The "short" list produced by @FoolRunning, updated and reorganized:
# Handled by SB already in some other way
* **BooksPresent**: List of books that are present in the project (handled by SB)   
* **Versification**: Versification used by the project (handled by SB - see #49)
* **LanguageIsoCode**: Language used by the project (handled by SB)
* **Language**: Language name (handled by SB)
* **FullName**: Full name of the project (handled by SB)
* **Name**: Short name/abbreviation of the project (handled by SB)
* **Guid**: The project ID (handled by SB)
* **Copyright**: Copyright information (handled by SB)
* **UsfmVersion**: USFM version used by the project (handled by SB)
* **FileNameBookNameForm**, **FileNamePrePart**, **FileNamePostPart**: Tells Paratext how to find a file for a particular book (should be handled by SB by describing which files correspond to which book)
# Slated to be handled by SB
* **Encoding**: Encoding of the text of the project (might be handled by SB - see #137)
* **TranslationInfo**: Basically the type of project (not completely handled by SB - see #93)
* **NormalizationForm**: Unicode normalization applied to the text (not yet handled by SB - see #138 )

***

It looks to me like everything in this file that we consider to be essential to PT is either handled or covered in a more specific issue, so can we close this?

**Comment by mvahowe** [comment]
The above settings file turned out to be old and missing some of the fun stuff. Here's another one, from a 2019 French project. 
[frc_settings_xml.txt](https://github.com/bible-technology/scripture-burrito/files/4287020/frc_settings_xml.txt)
