### ISSUE TITLE
File encoding

### ISSUE THREAD

**Issue by rdb** [bible-technology/scripture-burrito#137]
We should decide on the encoding of files in a Scripture Burrito, and document that.

I think there's no question about the encoding of the metadata—it should be UTF-8, because that's what JSON mandates.  The question is about other text files (such as USFM/USX).  Can we mandate UTF-8 without BOM (my preference)?  If not, should we add an encoding attribute to the metadata somewhere?

**Comment by mvahowe** [comment]
I think UTF8 for metadata is the way to go.

For ingredients, if we can't settle on UTF8, we may need multiple fields to specify encoding in different places. And I'd expect that to need to be specified on a per-flavor basis.

**Comment by rdb** [comment]
If we need encoding for ingredients, should we not put that in the ingredient section, since it determines how to read that file (since you can't read that file without knowing the encoding)?

**Comment by mvahowe** [comment]
Hmm. That might be the most flexible approach. But I'd like to know how often, and how unpredictably, encoding is likely to vary across ingredients first. Everything we add to ingredients needs to be maintained automagically as files are added, deleted or modified, so I think the overhead needs to be justified. If, say, we identify 2 roles in a textTranslation where different encoding might happen, we could handle that in the flavor details section.

**Comment by rdb** [comment]
For reference, these are the stats for the encodings for all projects on the PT Send/Receive server:
```
  11037   <Encoding>65001</Encoding>
    240   <Encoding>1252</Encoding>
      7   <Encoding>UBS-Slovenian_BS_Standard-2003.tec</Encoding>
      7   <Encoding>874</Encoding>
      7   <Encoding>1250</Encoding>
      6   <Encoding>936</Encoding>
      5   <Encoding>950</Encoding>
      4   <Encoding>kenya.map</Encoding>
      3   <Encoding>1251</Encoding>
      2   <Encoding>portdr.tec</Encoding>
      1   <Encoding>Windows-1251-Slavonic.map</Encoding>
      1   <Encoding>SILD-UNIC.tec</Encoding>
      1   <Encoding>PhilAnsiSIL.tec</Encoding>
      1   <Encoding>Latvian.map</Encoding>
      1   <Encoding>Hakka1252.map</Encoding>
      1   <Encoding>guinea.map</Encoding>
      1   <Encoding>BukarKey.tec</Encoding>
      1   <Encoding>baatonum.map</Encoding>
      1   <Encoding>Abidjan.map</Encoding>
      1   <Encoding>932</Encoding>
      1   <Encoding>1254</Encoding>
```
This suggests 97.4% of all projects use UTF-8.  Converting cp1252 to UTF-8 is trivial.  If we need to support custom encodings, that would get a lot trickier, however.

**Comment by FoolRunning** [comment]
> Can we mandate UTF-8 without BOM (my preference)?

That sounds fine to me. I don't think it's unreasonable to require legacy projects to upgrade to Unicode - there are tools to help with that. Tools that support other encodings (e.g. Paratext) could restrict the creation of SBs to only those projects that are Unicode.

If we allow non-Unicode encodings in SB, that means that every application that uses SB will need to support them (which seems like a lot of overhead for a very small percentage of projects). Especially if we start talking about having custom encodings included.

**Comment by mvahowe** [comment]
@FoolRunning I don't have data. @smorrison ? But I'm pretty sure that all our USX (and maybe all USX, period) is UTF-8.

Whatever the answer, I tend to agree that we should make the pain of non-UTF-8 a migration issue rather than passing it on to every consumer of SBs.

**Comment by smorrison** [comment]
@mvahowe As I'm sure we all know, XML can be self-declaring when the BOM is not present. All of our metadata is UTF-8, because we control that within our system. I don't know about USX itself though. I've never -seen- USX that's not UTF-8, but it's not mandated.

To Dan's original point, we could ensure that the XML-metadata declares itself UTF-8 (and apparently JSON must be UTF-8, which I didn't know). DBL historically takes a hands-off approach on the format or encoding of the resources that it's fed. i.e. I don't have a strong opinion.

**Comment by jag3773** [comment]
Agreed to use UTF-8 without BOM.

**Comment by jag3773** [comment]
Latest discussion today is to simply require UTF-8 without specifying whether the BOM is present.

@rdb Is there a reason why you prefer to mandate that BOM not be present?

**Comment by smorrison** [comment]
Unicode standard v5, section 2.6 (http://www.unicode.org/versions/Unicode5.0.0/ch02.pdf) says:

> Use of a BOM is neither required nor recommended for UTF-8, but may be encountered in contexts where UTF-8 data is converted from other encoding forms that use a BOM or where the BOM is used as a UTF-8 signature. 

i.e. the BOM is redundant in UTF-8 but required in UTF-16 and 32. BOM seems to be allowed in UTF-8 for consistency more than any technical requirement.

**Comment by rdb** [comment]
UTF-8 with BOM is very rare, and redundant, and readers should not be expected to be able to handle it.
