### ISSUE TITLE
Put back links from JSON Schema to doc tool

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#146]
@jag3773 I think I deleted some of your $$ voodoo from the schema files when I was first trying to make things work. Sorry about that. Can you put whatever is missing back and verify that the documentation is building correctly?

**Comment by jonathanrobie** [comment]
The tool we were using doesn't seem to work well. We need to find another tool.

**Comment by jag3773** [comment]
https://github.com/bible-technology/scripture-burrito/pull/182 actually fixed this for 0.2.0 docs.
