### ISSUE TITLE
Allow USX in source "variants"?

### ISSUE THREAD

**Issue by jonathanrobie** [bible-technology/scripture-burrito#167]
@mvahowe wrote:
> Thinking about the plan to use USFM rather than USX for default variants...

> One solution is to use USX everywhere.

Or at least allow USX in default variants.  In many applications, it would be easier for me to generate XML than to generate USFM and the data is not created using the editing window in a scripture editing application.

**Comment by mvahowe** [comment]
This is for Scripture textTranslations.

**Comment by jag3773** [comment]
@jonathanrobie can you describe the use case behind this so we can better determine if the spec supports this already or should support it?

**Comment by jonathanrobie** [comment]
I have two use cases in mind.

   1. Some programs generate USX source directly without using USFM
   2. Paratext now has a native XML authoring mode in alpha.  With this
   mode, it is possible to create USX directly in the editor

I think a source variant should be able to contain USX without USFM to
support these cases.

**Comment by jag3773** [comment]
Long term this might be a good addition, but for now it doesn't help with interoperability as many tools can only import USFM. e.g. Autographa, translationCore, etc.

**Comment by jonathanrobie** [comment]
This is not part of the Minimum Required to Declare Victory, and interop is our main goal, so I suggest we close this for this version, and revisit in the future.
