### ISSUE TITLE
Documenting flavors that don't exist yet?

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#174]
It looks like we opened these issues a long time ago. I don't think we have immediate plans to create these flavors, so can we close these issues and make new ones when we do have a plan?

- [ ] #16 
- [ ] #17 
- [ ] #18 
- [ ] #19
- [ ] #20

**Comment by jonathanrobie** [comment]
I would rather have these issues stay open.  It makes it easier to see what
kinds of things we still need to do.

**Comment by FoolRunning** [comment]
I agree with keeping them open. It doesn't look like any are in the 0.2 milestone, so they shouldn't be holding up any work.

**Comment by mvahowe** [comment]
They aren't holding up any work, it's just that "we" don't "still need to do" any of this, according to https://docs.burrito.bible/en/v0.1.0/extending.html

I'd really like us to drop our collegiate messiah complex. It's not our job to try to guess what everyone in the world needs and try to give it to them. If someone wants a flavor for syntax trees, there's a process for doing some preparatory work before talking to us. If no-one is doing that, why do "we still need to do" anything? If someone who does this doing finds that issue, they are likely to assume that it's all under control, which is the precise opposite of what we should be communicating.

**Comment by jonathanrobie** [comment]
Could we please focus on the things needed for the 0.2 milestone and worry
about this kind of question after that?  We have agreed not to bring in
these questions until after that point, closing issues because we have not
yet taken them on seems counterproductive.

**Comment by mvahowe** [comment]
Focusing on 0.2, and then things we may do before the Eschaton, is exactly why I'd like to close these issues. Between documentation tasks where there's nothing to document and use cases that have been untouched for 4 months and which aren't use cases for SB anyway, a significant proportion of all our issues are currently doing nothing but stopping us from seeing what we could actually be working on.

Also, by this logic, we could list every single thing we haven't done, and have no plan to do, and that no-one here is offering to do, which would give us a million completely useless issues. Generating lists in itself doesn't solve problems.
