### ISSUE TITLE
Create Test Data for audioTranslation

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#189]
## Definition of Done

* [x] Repository created at https://github.com/bible-technology/sb_audioTranslation
* [x] Automated testing with passing json-schema validation against `metadata.json`
* [x] All ingredients present and valid according to type and hash

**Comment by jtauber** [comment]
removed the recipe spec requirement

**Comment by jtauber** [comment]
Just need to source sample audio.

**Comment by smorrison** [comment]
There is public domain audio available at https://app.thedigitalbiblelibrary.org/entry?id=105a06b6146d11e7 (World English Bible, NT only)

The data for this (mp3s) is about 540MB, I've tar-gzipped it and placed it here https://drive.google.com/file/d/1oKmutfBKe22kwxpZjVOgm2U0TdFaDEa8/view?usp=sharing

**Comment by jtauber** [comment]
used 1JN subset from above.
