### ISSUE TITLE
Create Test Data for minimalTemplate

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#191]
## Definition of Done

* [x] Repository created at https://github.com/bible-technology/sb_minimalTemplate
* [x] Automated testing with passing json-schema validation against `metadata.json`
* [x] All ingredients present and valid according to type and hash
* [x] Associated realistic recipe spec, if applicable

**Comment by jtauber** [comment]
Completed 2020-09-17 (see repo)
