### ISSUE TITLE
Create Test Data for textTranslation

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#193]
## Definition of Done

* [x] Repository created at https://github.com/bible-technology/sb_textTranslation
* [x] Automated testing with passing json-schema validation against `metadata.json`
* [x] All ingredients present and valid according to type and hash
* [x] Associated realistic recipe spec, if applicable

**Comment by FoolRunning** [comment]
Just need to add the license information and this will be finished.

**Comment by FoolRunning** [comment]
This has finally been completed.
