### ISSUE TITLE
Create Test Data for textTranslation_derived

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#194]
## Definition of Done

* [x] Repository created at https://github.com/bible-technology/sb_textTranslation_derived
* [x] Automated testing with passing json-schema validation against `metadata.json`
* [x] All ingredients present and valid according to type and hash

**Comment by jtauber** [comment]
The textTranslation_derived metadata from the doc examples artifacts has ingredients like `release/text/USX_1/OTINT.usx`. Are those files something I could include in the test repo or should I completely fabricate new ingredients for this test repo?

Also, I can easily verify by hash but how much other validation should I do of ingredient file format?

**Comment by jtauber** [comment]
Regarding

> Also, I can easily verify by hash but how much other validation should I do of ingredient file format?

I notice that existing test repos don't have any automated testing even of hashing. Is that something we want to add to a validation suite?

**Comment by jag3773** [comment]
Yes, the current spec is very minimal on ingredient specification and/or validation. In general, we want to be more particular about ingredients (you know, Non-GMO, Organic, Gluten-Free, etc.).

**Comment by jtauber** [comment]
removed the recipe spec requirement

**Comment by jag3773** [comment]
You can use a subset of https://github.com/bible-technology/sb_textTranslation/tree/master/ingredients .

**Comment by jtauber** [comment]
Gospel subset moved over, realistic updates to metadata and size/checksums now work out.
