### ISSUE TITLE
Create Test Data for typesetScripture

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#195]
## Definition of Done

* [x] Repository created at https://github.com/bible-technology/sb_typesetScripture
* [x] Automated testing with passing json-schema validation against `metadata.json`
* [x] All ingredients present and valid according to type and hash

**Comment by jtauber** [comment]
removed the recipe spec requirement

**Comment by jag3773** [comment]
@smorrison to provide data for this.

**Comment by smorrison** [comment]
None of the existing print entries are unencumbered, and we shouldn't need to go through a licensing process to get sample data. 

I'm going to work with my co-worker Tomas to create a print-ready version of at least a portion of a freely-redistributable text early next week.

**Comment by smorrison** [comment]
@jtauber @jag3773 Attached is a render of Matthew from the Reina Valera 1909 (i.e. in the public domain). The included metadata is in the most recent form for DBL. 

[ReinaValera1909_print.zip](https://github.com/bible-technology/scripture-burrito/files/5460339/ReinaValera1909_print.zip)

**Comment by jtauber** [comment]
Thanks! I'm working now on getting the metadata.json to accurately reflect the DBL metadata.xml.

**Comment by jtauber** [comment]
Blocked by #225
