### ISSUE TITLE
Create Test Data for wordAlignment

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#197]
## Definition of Done

* [x] Repository created at https://github.com/bible-technology/sb_wordAlignment
* [x] Automated testing with passing json-schema validation against `metadata.json`
* [x] All ingredients present and valid according to type and hash
* [x] Associated realistic recipe spec, if applicable

**Comment by joelthe1** [comment]
No recipe specs identified. This has been completed and merged here: https://github.com/bible-technology/sb_wordAlignment
