### ISSUE TITLE
Create Test Data for xScripture

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#198]
## Definition of Done

* [x] Repository created at https://github.com/bible-technology/sb_xScripture
* [x] Automated testing with passing json-schema validation against `metadata.json`
* [x] All ingredients present and valid according to type and hash

**Comment by jtauber** [comment]
removed the recipe spec requirement

**Comment by jtauber** [comment]
done and managed to get an additional "finger painting" pun in there.
