### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#206]
Setup github action and metadata file for publishing package to PyPi.

**Comment by jtauber** [comment]
Where did we land on the `author_email` to use in the package descriptor?

**Comment by jtauber** [comment]
On the call Nov 12 2020 we decided I'd just use my email for author_email.

**Comment by jtauber** [comment]
Very early version now up at https://pypi.org/project/scripture-burrito/0.0.1/ (although much to do)
