### ISSUE TITLE
Use Case:  Identify the Owner and Latest Revision for a Translation Project

### ISSUE THREAD

**Issue by jonathanrobie** [bible-technology/scripture-burrito#209]
A resource server like DBL needs a way to identify the owner and latest revision for a translation project.   If several different translation editors are being used, on several machines, and the result is stored in more than one place, it still needs to know where to find the current authoritative source for any given project.

Possible solution:

- Identify one 'project owner' for each translation project - this is not a person, but an identifier identified by the URL of the authority
- The owner creates the authoritative identifier for a project 
- Additional identifiers are allowed as needed by various systems
- The 'owner identifier' should always be kept in the translation project so that the link to the authoritative source is not lost

This would require extending the SB metadata.

**Comment by FoolRunning** [comment]
This seems like it would create a lot of overhead for consumers of SB (i.e. they would be required to adopt whatever identification scheme the "owner" chose). I also don't understand why DBL needs to know the latest revision for a translation project. The user who uploads the SB to DBL should know that information.

**Comment by jonathanrobie** [comment]
I don't think DBL needs to know how to find the latest revision, I do think
it needs to know who to ask for the latest revision, which means it needs
to know which project repository owns the project and has the latest
version.  Once it knows that, the rest can be negotiated.

I could be wrong, of course.  What am I missing?

**Comment by FoolRunning** [comment]
Why would it need to know who to ask if it doesn't need to ask?

**Comment by jonathanrobie** [comment]
A publisher who uses DBL wants to know if there is a newer version of the text for a DBL resource or wants to know why a change was made, etc.  

The publisher contacts a DBL administrator. This administrator also has access to the project in Paratext or some other environment. The DBL resource should have sufficient information to let the administrator move to the Paratext environment or talk to someone who uses that environment and understand where to find the equivalent state of the project.

This basically amounts to being able to display identifying information in DBL so that the administrator knows where to find things.

**Comment by jag3773** [comment]
Related to #222 #75 #210

**Comment by jonathanrobie** [comment]
I think this works now that the creating system provides the identifier and
revision.  As long as we define identification and integrity constraints
correctly.

**Comment by jag3773** [comment]
OK, safe to close then @jonathanrobie ?

**Comment by jonathanrobie** [comment]
Before we close this, I think we need to define identification and
integrity constraints in the specification.

**Comment by jag3773** [comment]
Discussion around #208 and #227 have revealed that this use case is accounted for.
