### ISSUE TITLE
Rework Versification as part of a burrito

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#212]
Currently, versification is a standalone flavor but it should be built into at least the following flavortypes:

* Scripture
* Gloss
* parascriptural

**Comment by jtauber** [comment]
Does this mean shipping a `.vrs` file inside each SB that references to a versification system rather than just referring to it by name?

**Comment by FoolRunning** [comment]
Most projects have customized their versification in some way so it makes sense that they should be included with the project.

**Comment by jag3773** [comment]
Ideally, the current project's versification could be provided as a delta against a known "standard" versification.

I think @jonathanrobie and versification group was going to define how this happens (maybe they have already?).

For non-Scripture types, I think we just need to reference the versification scheme being used. For example, a set of translation notes shouldn't be able to customize a versification scheme, but it may be keyed to a BCV scheme and the tool just needs to know which one that is.

**Comment by FoolRunning** [comment]
> For example, a set of translation notes shouldn't be able to customize a versification scheme, but it may be keyed to a BCV scheme and the tool just needs to know which one that is.
But that versification scheme would probably be a customized version belonging to a project, would it not? If we just reference it "by name", then that means we need to have a name (or some designation) for every customized versification that exists.

**Comment by jonathanrobie** [comment]
To emulate the status quo, I think we have two reasonable options.

1. Each project's versification is a delta from "org", and is contained as
a versification file in a burrito, or
2. We support other standard versifications like "eng" by name and require
them to be available in a public place (e.g. the Copenhagen Alliance site).
A project's versification can also be defined as a delta from one of these
schemes.

In practice, many projects use the versification of an existing gateway
language translation, which suggests we might also want to be able to
specify diffs from:

3. A specific revision of a specific resource

I would suggest that we support all three.

**Comment by jag3773** [comment]
@jtauber to prep and then talk to @jonathanrobie about possible work needed in versification group.

**Comment by jtauber** [comment]
See #243 for discussion for @jonathanrobie to take to versification group.

**Comment by jtauber** [comment]
As discussed last week and in #243, all deltas will be expressed against **org** and no other versification system. They may have _originally_ been expressed as delta to some other versification system but, for the purposes of generating a burrito, the delta against **org** is calculated and that is all that can be in a burrito.

**Comment by jonathanrobie** [comment]
Yes, I agree.

**Comment by jtauber** [comment]
I think this is now going to be done as a new role for an ingredient which is a delta from the `org` versification to the versification used in the burrito. In which case I think #248 will cover it and this can be closed. But is there anything else that needs to be done? Is a role on an ingredient sufficient?

**Comment by jtauber** [comment]
as now covered by #248, this can be closed.
