### ISSUE TITLE
idServers - are they servers? authorities?  what expectations do we have for them?

### ISSUE THREAD

**Issue by jonathanrobie** [bible-technology/scripture-burrito#216]
The name idServer implies some kind of server that offers functionality we have not defined.  If these servers exist, what do we expect them to do, and how would someone with a Scripture Burrito use them?

Can a client running on a desktop or a smartphone create identifiers that a particular system understands?  I think using URLs to identify naming authorities is the best approach, I am not questioning that, but I think the interchange formats we create should say as little as possible about systems, requiring as little as possible to exchange data.

Many identification schemes that associate a prefix with a URL do not require a particular set of servers or any particular kind of software, they use the URL merely to identify the authority that owns the naming scheme.

I suspect we could simplify this and make it clearer by doing the following:

- Change the name so that it does not imply that a server needs to exist in order to have a naming authority.
- Remove statements that say that Scripture Burrito assumes the existence of "identity servers".

**Comment by smorrison** [comment]
Would it be enough to rename the section to 'authority'? Maybe have URL as an optional element in the element?

**Comment by jag3773** [comment]
Let's change this to `idAuthority` every where it shows up in the spec.

**Comment by jtauber** [comment]
Should it be `idAuthority` or plural `idAuthorities` (given it's currently plural `idServers`?

**Comment by jag3773** [comment]
Plural, since we are still maintaining it as a list.

**Comment by jtauber** [comment]
I'm also changing `idServer` under `identification` to `idAuthority`. 

There is, however, also a `idServerKey` that sometimes appears under (what is now) `idAuthorities`.

**Comment by jtauber** [comment]
I'm also presuming I shouldn't change anything under `proto_doc`

**Comment by jag3773** [comment]
Related to #227

**Comment by jag3773** [comment]
Several different entangled ideas:

- Location
- Naming
- Ownership - should not be construed with this field, the Agency section is for this.

Should the id and idAuthority be deference-able ?

**Comment by jtauber** [comment]
To me the fundamental purpose seems to be Naming, i.e. to be able to say: "authority X calls this burrito Y (version Z)"

We all agree that Ownership is not what this is for.

I still don't understand the purpose of the Location purpose. You have the burrito so you don't know need to know where to get it. What are the actual reasons for needing a location? To check if there are more up-to-date versions?

Note that I think there is a distinction between a deferenceable *burrito* and requiring that the *authority* information includes a link to the authority (or even to information from the authority on the naming system used).

**Comment by jonathanrobie** [comment]
Suppose I have a Kindle book and I know the Amazon identifier.  I know that Amazon is the authority that created the identifier but I do not yet know the location, I need to know Amazon's APIs or URI conventions before I can dereference it.

I think that's about right.  If a resource is available online, an authority could create a URI template so that a client can construct a URL that can be used to fine the resource.

**Comment by smorrison** [comment]
URLs explicitly about location, URNs are explicitly not, URIs encompass both.

Why not URNs? e.g. urn:sb:ptx:<project>:<revision>?

**Comment by jag3773** [comment]
Agreed that the purpose of this field is only naming–machine readable ids, in a technical sense.

**Comment by jtauber** [comment]
I've started discussions:

#232 
#233 
#235 

So perhaps we can close this issue.

**Comment by jtauber** [comment]
or alternatively, we keep this open and take it to mean "James to update documentation based on discussions"

**Comment by jtauber** [comment]
Once #246 and #232 are agreed on, I'll update documentation and can close this.

**Comment by jtauber** [comment]
as we have #216 to track the updates from #246 and #232, I'm closing this.
