### ISSUE TITLE
resolve fontType enum

### ISSUE THREAD

**Issue by jtauber** [bible-technology/scripture-burrito#225]
The current `fontType` definition is given as:

```
"fontType": {
    "type": "string",
    "enum": ["openType", "bitmap", "trueType", "type1"]
}
```

but based on the internal metadata for the sb_typesetScripture example, there seems to be a need for an `other` value.

**Comment by jag3773** [comment]
Simplest solution here is to drop fontType specification in the metadata because we can't think of a good use case for that information.
