### ISSUE TITLE
Do we need Versification as a standalone Burrito?

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#226]
What are the use cases for having standalone versification burritos?

**Comment by jag3773** [comment]
Possibly create folders inside of https://github.com/Copenhagen-Alliance/versification-specification which represent each scheme as a distinct SB.

**Comment by jtauber** [comment]
As I see it, the use case for a standalone versification burrito is to exchange a versification system without reinventing a metadata / packaging format for doing so.

For example, the individual versification systems under Copenhagen Alliance are just provided as raw data with no metadata. If metadata were to be added, would CA want to invent their own metadata format or could they just use SB? If the latter, that's our use case, in my opinion.

**Comment by jonathanrobie** [comment]
I think CA would create their own metadata format.

**Comment by jtauber** [comment]
If we don't need to exchange a versification system as a burrito, should this be closed?

It seems to me one might want to exchange versification systems between software, though.

**Comment by jonathanrobie** [comment]
I think we could close this.  I do think that we need to be able to refer to "the versification used in this other project" and do diffs from there.

**Comment by jag3773** [comment]
We've agreed to remove this in the next release. Note that #212 is still needed.

**Comment by jtauber** [comment]
I have a PR ready to go for this but want to briefly discuss on the call the fact this means there are now no examples of peripheral flavors.

**Comment by jag3773** [comment]
As discussed last week, that's OK. We'll add some other soon (lexicons, translation manuals, etc)
