### ISSUE TITLE
Tracking multiple ids in a Burrito

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#230]
Our example in #208 illustrates the need for further refining how we expect id sections to be persisted. If we are going to keep a particular system id in the burrito that is not the creator, then we probably want to remove the `revision` and `timestamp` field for that idAuthority because it would no longer be true.  Further example and refine are needed here.

**Comment by jonathanrobie** [comment]
I think it would be more precise to say this:  

- If you store a burrito without changing it, you should not change the `revision` and `timestamp`. 
- If you change anything in a burrito, you have created a new burrito. If you "edit" a burrito without changing the identification, all bets are off, the integrity of the overall system no longer holds.

For instance, if the send/receive server does not change the translation project, it can provide it, without change, to multiple clients.   If the send/receive server does change the translation project, it needs to create a new identifier and revision.  It should also identify the source burrito clearly.

**Comment by jtauber** [comment]
See #232 #233 and #235 for discussion. We could close this issue and move discussion there.
