### ISSUE TITLE
Create Minimal Burrito Examples for Each Flavor

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#238]

**Comment by jtauber** [comment]
Is this covered by the existing repos or are they not "minimal" enough?

**Comment by jtauber** [comment]
To clarify here, this is being done in https://github.com/bible-technology/sb_minimalFlavorExamples as the existing repos were not minimal.

**Comment by jag3773** [comment]
Can you link to that in the docs @jtauber ?

**Comment by jtauber** [comment]
Sure!

**Comment by jtauber** [comment]
Here's where we got last year:

* source
    * gloss
        * x
    * scripture
        * audioTranslation
        * embossedBrailleScripture
        * textTranslation
        * typesetScripture
        * x

**Comment by jtauber** [comment]
add textTranslation_derived and textStories

**Comment by jtauber** [comment]
Added the following:
* derived-scripture-x
* derived-scripture-textTranslation

A couple of observations doing so:
* `type/flavorType/name` was not required
* `recipe` can be empty

**Comment by jtauber** [comment]
Added:

* source-gloss-textStories

An observation doing so:

* required no changes specific to `textStories`

**Comment by jonathanrobie** [comment]
> * `type/flavorType/name` was not required
> * `recipe` can be empty

Both of these seem wrong.  The WG would like to make them required.

**Comment by jtauber** [comment]
`derived` burritos updated to reflect additional constraints in #302
