### ISSUE TITLE
Remove content that describes an XML representation that no longer exists

### ISSUE THREAD

**Issue by jonathanrobie** [bible-technology/scripture-burrito#251]
This text describes the format of metadata.xml, which no longer exists.

# Most Content in Text, not Attributes

This is partly a stylistic choice, but it also reflects the need to handle a wide range of UTF-8 characters in many fields. (It is considered bad practice to put localized strings into attributes.) Attributes are mainly used as qualifiers for the “main” content.

# Few Empty Elements, Many Optional Elements

The children of most root elements (identification, format, etc) are required. Many elements below that level are optional but, if they are present, they must contain content. This is to avoid confusion between a value that is unspecified and a value that is specified as an empty string. So

<name lang="eng">The Holy Bible</name>
<name lang="fra">La Sainte Bible</name>

is permitted, as is

<name lang="eng">The Holy Bible</name>

but

<name lang="eng">The Holy Bible</name>
<name lang="fra"/>

is not permitted.

# Order is Generally Unimportant

Most elements at all levels can appear in any order (or interleaved, in the terms of XML schema). Exceptions include a few elements that must appear as the first children of the root element and publication structures which communicate a specific content order.

**Comment by jtauber** [comment]
Part of an overall sweep of all existing documentation I'm doing as part of 0.4

**Comment by jtauber** [comment]
this is addressed in #270
