### ISSUE TITLE
JSON representation of VRS needs to handle one-to-many mappings

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#253]
Right now the mapping section of the "vrs-as-json" schema looks something like this:
```
        "mappedVerses": {
            "propertyNames": {
                "$ref": "#/definitions/bcvRange"
            },
            "additionalProperties": {
                "$ref": "#/definitions/bcvRange"
            }
        },
```
I don't think this handles one-to-many mappings, eg
```
PSA 51:0 = PSA 51:1
PSA 51:0 = PSA 51:2
```
In this case we have one property but need to represent two BCV ranges. This happens in standard versifications, and happens a lot more when mappings are reversed. Something like

```
PSA 51:0 = PSA 51:1-2
```
will create problems since existing VRS logic says that ranges have the same  number of verses on each side.

I think that the cleanest way to address this is to make the properties an array of BCV ranges. (In the majority of cases there would be exactly one BCV range in each array.)

**Comment by jag3773** [comment]
@jonathanrobie Can the versification working group take a look at this?

**Comment by jonathanrobie** [comment]
Moved to https://github.com/Copenhagen-Alliance/versification-specification/issues/16

**Comment by jag3773** [comment]
Looks like it's actually at https://github.com/Copenhagen-Alliance/versification-specification/issues/15, closing this for now.
