### ISSUE TITLE
Fix first list on documentation intro page

### ISSUE THREAD

**Issue by RobH123** [bible-technology/scripture-burrito#291]
Seems that the first list [here](https://docs.burrito.bible/en/develop/) suffers from a likely search-and-replace error, instead of having a link for Sign Language to [here](https://docs.burrito.bible/en/develop/flavors/scripture_sign_language_flavor.html).

-    [Scripture Text](https://docs.burrito.bible/en/develop/flavors/scripture_text_flavor.html#scripture-text-flavor)
-    [Scripture Print](https://docs.burrito.bible/en/develop/flavors/scripture_print_flavor.html#scripture-print-flavor)
-    [Scripture Audio](https://docs.burrito.bible/en/develop/flavors/scripture_audio_flavor.html#scripture-audio-flavor)
-    scripture_sign_language_flavor
-    [Scripture Braille](https://docs.burrito.bible/en/develop/flavors/scripture_braille_flavor.html#scripture-braille-flavor)
-    [Scriptural Text Stories](https://docs.burrito.bible/en/develop/flavors/scriptural_text_stories_flavor.html#scriptural-text-stories-flavor)

**Comment by FoolRunning** [comment]
We're aware of the problem and are looking into it. But it's nice to have this issue here so we remember. 😃 
@jag3773, @jtauber

**Comment by FoolRunning** [comment]
This has been fixed
