### ISSUE TITLE
Consider Simpler Identification of Scripture Burritos

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#293]
It's currently not easy to tell if a zip file is a burrito without running the schema validation or visually looking for flavor details.

Possibly rename `metadata.json` to `scripture_burrito.json`.

**Comment by jtauber** [comment]
Three options:

1. change the schema to explicitly mention scripture burrito; either (a) add a new fixed property that indicates it's a scripture burrito (e.g. `"format": "scripture burrito"`); (b) include identification as scripture burrito in the version string (e.g. `"version": "scripture burrito  1.0.0-rc2"`)
2. change the name of metadata.json (e.g. `scripture_burrito.json`)
3. include an additional file alongside metadata.json whose existence and content indicates this is a scripture burrito (e.g. a `mimetype` file like EPUB)

**Comment by jtauber** [comment]
Note that even though the documentation currently says the file should be called `metadata.json`, the examples in the repo itself (as opposed to the ones in separate repos) are all named differently.

**Comment by jag3773** [comment]
> Note that even though the documentation currently says the file should be called `metadata.json`, the examples in the repo itself (as opposed to the ones in separate repos) are all named differently.

Right, because they are all in the same folder!

**Comment by jtauber** [comment]
> Right, because they are all in the same folder!

Exactly. But even our own examples aren't using `metadata.json` in that context :-)

**Comment by FoolRunning** [comment]
FWIW, my vote would be to just add something in the **metadata.json** file that indicates it's a SB (e.g. ``"format": "scripture burrito"``). This is probably the most minimally breaking change we could make, and loading the metadata file should be very quick (i.e. I don't think it's an issue to require the file to be read to determine if it's a burrito).

**Comment by jag3773** [comment]
I agree @FoolRunning... Let's do that @jtauber... add `"format": "scripture burrito"` to the schema and let's release it as rc2.
