### ISSUE TITLE
Update text stories example Burrito

### ISSUE THREAD

**Issue by joelthe1** [bible-technology/scripture-burrito#294]
The example shown in the [Text Stories Scripture Burrito]( https://github.com/bible-technology/sb_textStories) needs updating to the latest version of the schema.

**Comment by jtauber** [comment]
all of the examples in other repos now need updating. I'm working through them.

**Comment by jtauber** [comment]
wow, this was _never_ valid but getting there :-)

**Comment by jtauber** [comment]
Okay, validates!
