### ISSUE TITLE
scripture_flavor_type.schema.json has invalid json

### ISSUE THREAD

**Issue by bind-almir** [bible-technology/scripture-burrito#310]
Hello, there is an extra comma on line 40 in the `scripture_flavor_type.schema.json`  which makes the JSON invalid.

https://github.com/bible-technology/scripture-burrito/blob/master/schema/scripture_flavor_type.schema.json#L40

**Comment by jtauber** [comment]
I do not believe this file is being used. No tests were failing because of the extra comma.
