### ISSUE TITLE
Overall Design Image

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#33]
Any revisions needed to this image before it goes on the [Overall Design](https://docs.burrito.bible/en/latest/metadata_design.html) page?

![SBOverallDesign](https://user-images.githubusercontent.com/107731/62296968-3a43ba80-b43e-11e9-8a6b-f1d8982edb2a.jpeg)

*edited to remove the errant 'l' before WordAlignment*

**Comment by mvahowe** [comment]
Right now the names of flavors in the schema are camelCase rather than CapitalCamelCase. I don't know which is considered correct by the grammar police, but, either way, the schema and diagram should probably agree.

**Comment by jag3773** [comment]
I think the graphic is using camelCase, right?  I'm just eliding the first part with "..." in many of the examples.

**Comment by mvahowe** [comment]
Oh, Ok, I see now.
