### ISSUE TITLE
Make systemIds generic

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#43]
# Making systemId generic in Scripture Burrito

## Context

Scripture Burrito is based on DBL Metadata. The current plan involves

* identifying library-type organizations by URL (which means ICANN gets to ensure uniqueness and means no-one in our ecosystem needs to run the definitive registry for organizations)

* mapping organizations to prefixes within the scope of each Scripture Burrito document

In DBL 2.x we have systemId types that are known prefixes for organizations. In each case we specify the format of ids, as well as any other content. In Scripture Burrito, the plan is to allow any prefix or prefixes, correponding to any URL declared elsewhere, with no whitelist of organizations.

One thing we lose here is the ability to check the syntax of ids via the schema. (For example, right now the schema requires DBL ids to be 16 hex characters and Biblica ids to be an integer). But there are other ways to do this (probably involving a standard for querying Scripture Burrito servers to get this kind of information.)

Apart from that, DBL will need to coerce all the existing systemId variants into the new, generic system. For GBC, PT Reg, TMS, REAP, Biblica and DBP this seems trivial since the only child in each case is the id. However, the paratext id (which I believe is used for PT resources) contains

* id

* csetId

* name

* fullName

* optionally, baseId and baseName

That won't work within a generic scheme (unless we allow anyone to put literally anything inside any systemId, which is a terrible idea). So we need to understand why DBL has those fields in the first place, how much of that information is still needed, whether this is a "how we implement PT resources today" thing or something about translation scenarios in general, and how we could move whatever information we will need in the future to more appropriate locations.

Extract from the schema attached for completeness.

```
gbcSystemId =
  element systemId {
    attribute type { "gbc" },
    gbcElements
  }

gbcElements =
  element id {
    gbcId
  }

ptregSystemId =
  element systemId {
    attribute type { "ptreg" },
    ptregElements
 }

tmsSystemId =
  element systemId {
    attribute type { "tms" },
    tmsElements
  }

tmsElements =
  element id {
    tmsId
  }

ptSystemId =
  element systemId {
    attribute type { "paratext" },
    ptElements
  }

ptElements =
  element name { lenGe2String } &
  element fullName { lenGe2String } &
  element csetId { lenGe2String }? &
  element id { ptId } &
  (
    element baseId { ptId } &
    element baseName { lenGe2String }
  )?

ptregElements =
  element id { ptregId }

reapSystemId =
  element systemId {
    attribute type { "reap" },
    reapElements
  }

reapElements =
  element id { reapId }

biblicaSystemId =
  element systemId {
    attribute type { "biblica" },
    biblicaElements
  }

biblicaElements =
  element id { biblicaId }

dbpSystemId =
  element systemId {
    attribute type { "dbp" },
    dbpElements
  }

dbpElements =
  element id { dbpId }
```

**Comment by mvahowe** [comment]
@rdb and I spent a while looking at what is currently in DBL. This has raised several questions that I think only the PT team can answer. But, in terms of Scripture Burrito, it looks like we could drop most of these fields.

**Comment by mvahowe** [comment]
After further feedback from Eric Pyle, my understanding is

* We definitely do not need csetId

* fullName should be the same as identification/name as of Paratext 8, so we do not need fullName in the systemId

* I'm still not sure how important baseId and baseName are but, in a future, "burritos everywhere' world, I think we'd handle this kind of thing via relationships at a higher level.

This leaves what DBL calls identification/systemId[@type='paratext']/name which I believe PT Reg calls the "short name". My understanding is that this name is "chiselled in stone" (@rdb) when the project is created, and that it is used in various places as a primary key for the project. (It isn't clear to me if this field is strictly immutable.)

If all the above is true, then I think we can safely move to a generic systemId system where \@type corresponds to a URI in the document and the text() value is an id, the format of which will not be schema validated.

My remaining question, which we do not need to answer for SB, but which PT and DBL will need to answer, is whether the primary key to a PT project is going to be the id (first commit UUID) or the shortName or both. Personally, I would argue strongly against attempting to support two primary ids for the same system. At best it's redundant, at worst (as soon as the two primary keys diverge) it's a recipe for confusion.

So, if the shortName is 100% stable with respect to a project, I'd suggest that SB stores that as the "id", because it's more archivist-friendly. If the shortName is liable to change within the lifespan of a project, SB should store the first commit uuid as the id. And if PT insists on providing two primary keys, I think we can fudge that via two different PT-related URLs, one for each primary key.

**Comment by rdb** [comment]
@mvahowe The difference between the short name and the GUID is that the short name is not guaranteed to uniquely identify a project.  For that reason, if we will store one ID, it should be the GUID.

If we are going to store both, I would either propose that the move the short name to somewhere more global (in the identification section).  Another crazy idea is that the Paratext ID syntax encompasses both; something along the lines of `sburrito:pt:a83bf183..da4f31:SHORT` ?

**Comment by mvahowe** [comment]
PR #46 addresses this issue.
