### ISSUE TITLE
Licensing Examples

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#48]
The [licensing section](https://docs.burrito.bible/en/latest/metadata_licenses.html) of the docs is intentionally generic, we at least need more examples on the page and possibly we should consider a standardized way of referencing public licenses?

**Comment by mvahowe** [comment]
I think we have most of the options, eg

* public domain

* all rights reserved (ie no license)

* a URL to an external license

* a path to a license present in the burrito resources

I think that, eg,

https://creativecommons.org/licenses/by-nd/4.0/

is pretty explicit. Personally, I don't think we want to get into maintaining an enum of every possible way to license things.

**Comment by joelthe1** [comment]
Do you think we should have a field to allow for the name of the license? Especially for the cases when we point to other files that have the license (URL or file in SB)?

**Comment by mvahowe** [comment]
I'm not opposed to extra fields. I experimented with some options. My concern is who decides the name of a license, complete with capitalization, whitespace etc. If the name isn't consistent enough to use as a key, I'm not sure how much added value it gives us compared with a URL.

**Comment by joelthe1** [comment]
I see that but also what about the case when an org really wants an easy way to know the license of its SBs and their program has to dig in to files/URLs to find that.

**Comment by mvahowe** [comment]
The thing I think we have to bear in mind is that it's not an org thing, it's a whole Bible world thing, because it's a portability standard. So this isn't something where one org can decide to use a field one way and not worry about how everyone else is using it. If we have names for particular licenses, that's only useful if there's an agreed name that everyone uses for that license. I think that leaves us maintaining the enum of license names. Are you aware of another option?

Also, URLs are used for XML namespaces, and in our current idServer proposal, ie it's not unusual to use a URL as an identifier.

**Comment by joelthe1** [comment]
I think you are right. So basically have a name field but with enum values to choose from? And I can't think of another option other than maintaining the enum, in which case we could have a popular set with custom ones with `x-`?

**Comment by mvahowe** [comment]
Ok, in that case maybe you could try to assemble the enum? The next issue is that, if we're not careful, we end up with 2 primary keys. ie we could have a name that points to one license and a URL that points to a different license, and the answer to various questions is therefore different depending on the implementational details of the toolchain. So, ideally, we'd police the mapping between those two fields.

**Comment by mvahowe** [comment]
Here's a list of open source licenses. I don't think this includes non-latest versions.

https://opensource.org/licenses/alphabetical

(Some of these are extremely unlikely to be used for some flavors, but I wouldn't rule out someone using most of them for, say, a JSON resource aimed at AI.) I think there are 6 CC licenses each in at least 4 versions. Older versions may well be used in existing content.

**Comment by joelthe1** [comment]
> Ok, in that case maybe you could try to assemble the enum? The next issue is that, if we're not careful, we end up with 2 primary keys. ie we could have a name that points to one license and a URL that points to a different license, and the answer to various questions is therefore different depending on the implementational details of the toolchain. So, ideally, we'd police the mapping between those two fields.

Or for the cases we have an enum value for, we do not allow the user to specify a source because we maintain it. In case it is required, we allow it in the custom type?

Although, maintenance of that list is another thing. If we don't want to do that, I'm okay with leaving it under specified.

**Comment by mvahowe** [comment]
I know I don't want to maintain that list :-) @jonathanrobie What do you think? If we want to offer some easy options, maybe we could start with quite a short list, eg, the CC licenses plus maybe MIT and a few other OSS licenses, and have a knownName alternative (for want of a better label) to the current 4 license options? If we had a short list like that, I suspect that DBL and others would provide it via the UX, which would encourage use of one of those options in new projects.

**Comment by joelthe1** [comment]
> If we had a short list like that, I suspect that DBL and others would provide it via the UX, which would encourage use of one of those options in new projects.

This is partially my motivation too.. But maintenance might be time consuming :/

**Comment by mvahowe** [comment]
In general, the best is the enemy of the good. An exhaustive and systematic list of licenses would be cool, but negotiating and maintaining that feels to me like a full-time, open-ended project.

I think that providing a URL to the license is a workable system. The idea isn't to perform deep semantics on the contents of the web page, it's to use the URL itself as a key. I'm not convinced that

"Creative Commons BY-ND License v4.0"

is actually any easier to parse than

"https://creativecommons.org/licenses/by-nd/4.0/"

Or, we could offer the 6 Creative Commons licenses, plus Christian Commons, plus 6 OSS licenses (say BSD, MIT, Apache, GPL2, GPL3 and LGPL). One of those ought to be close to what most people want and, if people want something else, they have options.

**Comment by jag3773** [comment]
I think an enum along the lines of CC licenses plus BSD, MIT, Apache, GPL2, GPL3 and LGPL could work reasonably well.

However, I'm partial to the idea of just using the URLs.  I'd be in favor of showing half a dozen examples in the documentation of the CC or OSS software licenses.

@joelthe1 I think that the Front matter section will still be a good way to provide human readable copyright, licensing and trademark information.

**Comment by jonathanrobie** [comment]
If we have the URLs, we could create a search mechanism that could find things that are "free for non-commercial use", "public domain", "free for commercial use", "allow derivatives", etc. based on someone carefully reading the associated licenses once.

I would like to have that search mechanism.

**Comment by joelthe1** [comment]
@jonathanrobie, having such a mechanism is good but may not be the best use of our time upfront. Also, URLs aren't the only people would specify licenses.
Also @jag3773, calling it front-matter makes more sense, since we need not try to use it as a 'key'.

**Comment by RobH123** [comment]
Thinking about multiple licenses:

I know that software sometimes comes with multiple licenses, i.e., a choice of licenses. Presumably that isn't likely to apply to SB contents?

Also, isn't it usual for Bibles to have geographical licenses, e.g., one company publishes NIV in US, another in UK? Could a Bible translation be commercial/restricted in the US, etc., but open-licensed in other countries?

BTW, **The Countries Section** doesn't describe what it even means -- the country it was produced in, can be used in???

**Comment by jag3773** [comment]
@RobH123 Yes, a text can have multiple licenses, but it may only be used under the terms of one at any given time.  Hence, you could two identical Scripture Burritos except that they are distributed with different licenses defined therein.

In the current specification, the notion of dual licensing would need to be maintained a part from the SB metadata (e.g. in whatever system is managing the licenses).  I'm open to the idea of allowing multiple licenses to be defined in the specification but the current configuration seems suitable since a SB is a snapshot of a project intended for interchange between ecosystems.
