### ISSUE TITLE
Canon/Versification Format

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#49]
We need a working group, ideally from Copenhagen-Alliance, to tackle the data format question of versification systems.

Related to #26

**Comment by jonathanrobie** [comment]
I will spin one up.  I have some members already.  I expect it to be based on:

https://github.com/ubsicap/versification_json

**Comment by mvahowe** [comment]
I've added some documentation for the current versification flavor. I suggest we close this issue until we receive feedback from Jonathan's group.

**Comment by jag3773** [comment]
Current spec has this as a stub and will be fleshed out in more detail later.

**Comment by mvahowe** [comment]
I'm encouraging the Versification WG to either address the issue of SB formats or hand it back to the SB WG.

**Comment by jag3773** [comment]
@jonathanrobie we could certainly use an update on where things stand.

**Comment by mvahowe** [comment]
There's a proposal to include custom.vrs in textTranslations on #52. I would like to use the JSON format we talked about. I hope that the versification committee will be able to sign off on this soon.

**Comment by mvahowe** [comment]
The versification working group looked at this. We're going to see if we can sign off on a proposal at the next meeting, in 2 weeks.
