### ISSUE TITLE
What labels do we need for our issues list?

### ISSUE THREAD

**Issue by jonathanrobie** [bible-technology/scripture-burrito#58]
What labels do we need to maintain our issues list?

The default labels are designed for code, not specifications.  I started deleting some of these, but I decided to just add all the remaining ones to this issue just for fun. What states do we need to support with labels as we move from, say:

- An issue to discuss
- A requirement or use case
- One or more designs to consider
- A decision
- Text in the specification that reflects the decision
- Review in the wider community

Or is there a better way to think of this workflow?

**Comment by mvahowe** [comment]
I just unilaterally changed the labels (which we weren't using) and then applied them to all our issues. We can change them all again if necessary. I've aimed for categories that tell us what needs discussion and what needs implementation.

**Comment by jag3773** [comment]
Good idea, I also added a Flavor label to track discussions that relates specifically to flavors...

**Comment by mvahowe** [comment]
If we close this we can get rid of the "discussions about labels" label. (Can we speak of "closing a label"? Do we need an issue for this and, if so, how should I label it?)
