### ISSUE TITLE
Original languages not mentioned in introduction

### ISSUE THREAD

**Issue by RobH123** [bible-technology/scripture-burrito#64]
Congrats to the team for this early release! Some impressive thinking.

I notice in reading the **introduction** that the Bible translation process and Bible translation publishing is mentioned, but there's no mention as to whether or not the SB is also intended for original texts (i.e, Heb, Greek manuscripts, etc.)?

Thinking about this, it seems that USFM (and thus also USX) is designed for Bible translation and not for original texts, i.e., it doesn't contain native markup for qere/ketiv, apparatus, etc.

I have no idea what format the Paratext and BART source language packages store their information in, but perhaps that format could also be documented and made an option???

NOTE: I realise that some of these questions may be answered as I read further thru the spec, but either way, seems it might not be bad to mention the intended inclusion or exclusion of original/source (best terminology?) language texts in the SB intro.

**Comment by RobH123** [comment]
Reading on in **The Type Section**, it seems there that original language texts are **not** meant to be included in the SB?

Or if that's not indeed correct, it seems that either a new _flavor_ and or least a new _flavorType_ for _scriptureText_ would be required here.

**Comment by mvahowe** [comment]
Hi @RobH123, congratulations on providing the most rapid feedback on our proposal!

This is an interesting question. It would be helpful if you could expand on the challenges you see in representing original languages.

To answer one of your questions, I'm almost certain that Paratext currently stores all its "resources" in DBL in a format based on Paratext projects, so the text itself will be in USFM. There may well be additional stand-off content. @FoolRunning?

Whatever the answer, you are right that we should document it.

**Comment by FoolRunning** [comment]
Paratext stores the original language texts in straight USFM format.

**Comment by jag3773** [comment]
@RobH123 Good comment, I think our expectation was that they would be represented in USFM or USX.

However, you raise some valid points about the difficulty of encoding some of the original language features in those data formats.  I'm thinking particularly of the complexity required to encode a full textual apparatus for a Greek NT in USFM.  It's likely possible but I wonder if it's advisable?

There may be value in adding an original language flavor if for no other reason than most applications will want to display or interact with them differently than a translation.

**Comment by jag3773** [comment]
Note that this issue will now relate to the issue of: Do we want to indicate that a burrito contains original language (or source language) content.

I've opened another issue (#69) entirely for the question of whether or not that should be a different data format.
