### ISSUE TITLE
int abbreviation not intuitive

### ISSUE THREAD

**Issue by RobH123** [bible-technology/scripture-burrito#65]
In **The Ingredients Section** https://docs.burrito.bible/en/v0.1.0-beta/metadata_ingredients.html, the snippet shows **intnt** and **intMat**. I was totally puzzled as to what these _integers_ or _internal_ versions were until getting to the last line on the page where I discovered it means _introduction_.

If it was changed to intront and introMat it would be so much more intuitive.

**Comment by mvahowe** [comment]
@RobH123 That's a fair point. The peripheral names in Scripture Burrito are derived from USFM3:

https://ubsicap.github.io/usfm/usfm3.0/peripherals/index.html

Personally, I think it would be confusing for SB to introduce small but significant deviations from USFM. (We did include intMAT etc to handle book introductions which, in USFM, tend to be prepended to the canonical text.)

**Comment by klassenjm** [comment]
The 'int' form is taken from the INT book ID in a (yes, Paratext) scripture project, and has been in use for many years. I don't think we want to revisit the identifiers documented in USFM 3 at this point. That would be somewhat more painful than a quick look at the reference for what int means. Hopefully 'int' will become more acceptable / natural with a bit of use?

**Comment by neutrinog** [comment]
Explaining what 'int' means sooner in the documentation could be helpful. I was also stumped for a bit.
