### ISSUE TITLE
Observations about scripturePrint reflowable convention

### ISSUE THREAD

**Issue by klassenjm** [bible-technology/scripture-burrito#68]
SB 0.1 beta specifies two variants for scripturePrint - PDF `<contentType>pdf</contentType>' and Tagged Text `<contentType>inDesignTaggedText</contentType>'.

The current documentation associates the PDF variant closely with requirements for print on demand (POD), where "POD assumes a fixed page layout". I'm finding this association / explanation of the PDF variant to be awkward and perhaps misrepresenting what a scripturePrint burrito might (most commonly) be intended to represent. It seems to me that scripturePrint is in fact a digital packaging of content which, if printed, would accurately _re-produce_ a known print publication, or known intended print image. In that sense any scripturePrint would normally be a packaging of content which assumes (offers) a fixed page layout. The only unique thing about POD is that - today - most of the digital print equipment expects a restricted subset of sizes (and ideally a certain amount of margin / white space.) - and the `<pod>` element summarizes that this scripturePrint conforms.

A major value of having a scripturePrint archive is that it is a copy of the content which will accurately reproduce a known fixed layout on commonly available print systems. 

I'm unsure about the content of scripturePrint being explicitly presented as 'reflowable'. Typically, an amount of time and effort (more and less - and maybe minimal effort - depending on the design and intent) has gone into producing a scripture PDF file, in order to validate that this printable form is correct. Tagged Text is an intermediate format toward the printable output. Suggesting that InDesign Tagged Text is reflowable is only true _to some extent_. It has to be interpreted. To work, it has to be attached to a stylesheet in InDesign. The stylesheet could be included (or not) in the tagged text file. And it is not certain that all of the expected (required) page elements will be rendered through the tagged text content (e.g. footnotes _could_ be defined, and if included would then be rendered according to the limits of formatting options which InDesign can produce for footnotes).

RTF is also reflowable etc.

You could say that Tagged Text is a component of "source" content within a scripturePrint burrito ?

Should the first class element for scripturePrint simply be PDF, period? It is the defacto format which represents the industry-wide printable _image_ of something known to _have been printed_, or to be _printable as intended_ by the creator. (there are some factors to consider about color handling and PDF version etc. - but PDF is the best place to capture the print intent) 

A minor issue - the definition of the Tagged Text Variant says _"An InDesign Tagged Text (.indd) file with a scopeOrRole of “printFlowable”_. The extension `.indd` is an InDesign document itself. Tagged Text could have a variety of extensions - but typically just `.txt`. A creator of tagged text might decide to on a convention of `.idtt` - but there is no expectation.

**Comment by jag3773** [comment]
@klassenjm You know far more about this than I do, what you've proposed is fine with me.  Not sure if there are other opinions on this?

Certainly on the scripturePrint part, I'm in favor of constraining that to a PDF.

**Comment by mvahowe** [comment]
This was essentially a Biblica idea, and I've never received any further information that would enable us to move forward with this. Shall we close it unless/until there is more interest in this feature? That would mean that, for now, the "print" flavor would be PDF only.

**Comment by mvahowe** [comment]
I have asked Biblica what they would like to do.

**Comment by mvahowe** [comment]
I still have no feedback from Biblica, and I don't think we can proceed without it, since this was their idea, so I suggest we remove this convention from the 0.2 spec.
