### ISSUE TITLE
Original Language Data Format

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#69]
A spin off issue from #64 .

Is there value in creating a working group to figure out whether or not it would be advantageous to have a different type of data encoding for original (or source) language materials?

**Comment by mvahowe** [comment]
I think there's value if someone out there actually wants to solve a problem this way. I don't think we should be making hypothetical needs into action points for us. Someone asked this question when reviewing the documentation, why not invite him to make a case for an original language data format (pointing him to the "extending SB" guidelines)?

**Comment by mvahowe** [comment]
Is there an action point here? If not, can we close this? (I think we agreed that, for now, we were not providing any specific support for original languages. If that changes we can start a new issue with some specifics.)

**Comment by jag3773** [comment]
If someone writes up and implements a spec for this, SB working group would be happy to review and include if appropriate.
