### ISSUE TITLE
Investigate generating documentation from JSON schema

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#71]
Check to see if json-schema has support for inline documentation or some other feature that can be built into something like an API reference.

**Comment by jag3773** [comment]
@rdb Did you look into whether we can auto generate some documentation from the JSON schema ?

**Comment by jag3773** [comment]
Some possibilities for future reference:

* https://blog.cloudflare.com/cloudflares-json-powered-documentation-generator/
* https://github.com/AnalyticalGraphicsInc/wetzel
* https://github.com/adobe/jsonschema2md

**Comment by rdb** [comment]
These are the Sphinx extensions I found:
* https://pypi.org/project/sphinx-jsonschema/
* https://pypi.org/project/sphinx-json-schema/

**Comment by jag3773** [comment]
Giving this an initial test, looks like https://pypi.org/project/sphinx-jsonschema/ is going to work well enough, I'll create a PR for demonstration purposes and feedback.

**Comment by jag3773** [comment]
This is working and visible in the `develop` branch, docs at https://docs.burrito.bible/en/develop/schema_docs/index.html .
