### ISSUE TITLE
Lossless Round Tripping of Projects

### ISSUE THREAD

**Issue by jonathanrobie** [bible-technology/scripture-burrito#79]
> Scripture Burrito is intended to allow lossless roundtripping of projects between ecosystems. This depends to some extent on references to ecosystem servers that enable reconnection with different ecosystem-specific contexts.

Do we really believe this?  I think a project includes information about the people, project status, etc. that we do not intend to support in Scripture Burrito.

**Comment by mvahowe** [comment]
The question here seems to be how to define a project. The wider that definition, the harder it is to roundtrip. So what's our working definition of a project? Also, ecosystem servers provide a route to conversations etc, providing we have an agreed API.

**Comment by jonathanrobie** [comment]
Does SB need a definition of a project?  If so, what should it be?

**Comment by mvahowe** [comment]
Your use case uses the word "project". What does that word mean? If it means "whatever anyone wants it to mean", I'm not sure we can say anything at all about the use case. It might mean "a recipe for crême brûlée".

**Comment by mvahowe** [comment]
I suspect that we need a word for "what can travel in a portable manner between system via a SB" and another word for "the complete human and technological system that surrounds an instance of Bible translation". The text of a translation obviously fits within the first definition. I would say that conversations about the translation don't. I think there's a discussion to be had about, eg,hyphenation dictionaries.

**Comment by mvahowe** [comment]
See #52 which I think frames the question in a way we could answer, ie how much of a PT project needs to be portable?

**Comment by mvahowe** [comment]
Personally, I think we can only answer this question empirically, ie we do what we can and find out how lossless the result is. We have other issues such as #52 which are trying to nail down the specifics. So can we close this?
