### ISSUE TITLE
Ecosystem servers

### ISSUE THREAD

**Issue by jonathanrobie** [bible-technology/scripture-burrito#80]
> Scripture Burrito assumes the existence of ecosystem servers that provide ids for users, organizations and projects, and stores information to enable that server-hosted context to be discovered.

Do we really believe there must be ecosystem servers along these lines?  Anything that creates unique IDs should work fine, no?

Do we plan to flesh out a mature concept of ecosystem identity servers? I hope not ...

Also:  the need for unique identifiers is a system constraint, not a use case.  It does not belong in the Use Cases section.

**Comment by mvahowe** [comment]
Use case: "As a user I want to be able to describe a project in a way that uniquely identified that project across all systems."

I absolutely imagine defining an API for ecosystem servers. If we don't do it, someone else will do something that will become the de facto definition.

**Comment by jonathanrobie** [comment]
If I have a GUID that identifies something, is that good enough?  I can do
that on a local client without connectivity.

Is the requirement to have unique identifiers, or to have identity servers?

**Comment by mvahowe** [comment]
Is lossless roundtripping a requirement? If so, we probably need to get context from somewhere. If it isn't, maybe we don't. Is validating claims that a SB originates from a particular ecosystem a requirement? Should it be possible, given access permissions, to "find" any user or org mentioned in a SB? And so on.

**Comment by mvahowe** [comment]
At this point we seem to be proceeding with idServers, so can we close this?
