### ISSUE TITLE
confidentiality requires clarification

### ISSUE THREAD

**Issue by rdb** [bible-technology/scripture-burrito#90]
The current documentation has only this to say about the confidentiality field:

> confidentiality
> ===============
> 
> This contains
> 
> * metadata (required)
> 
> * source (optional)
> 
> * publications (optional)
> 
> each of which contains one of
>  
> * unrestricted
> 
> * restricted
> 
> * private

However, I could not find further explanation of what is and isn't exactly covered under these settings.  I think we should document the precise scope more clearly, and the differences between restricted and private.  If you ask me, we should also create a clear policy on what implementations are and aren't allowed to do in the varying levels of confidentiality, and possibly, what the behaviour should be if some of these elements are missing.

**Comment by mvahowe** [comment]
The inspiration for this was SIL's REAP, which has a much richer confidentiality model than DBL (which has a single flag). I agree that this needs precise documentation, and that we need to see how well it handles all use cases. (DBL isn't much help here since its existing model is so limited.)

It was clear in my mind that "unrestricted" meant "anyone can see it" and "private" meant "only the owner can see it". "restricted" was supposed to be something along the lines of "see license conditions".

We might also want to consider finer-grained permissions for metadata, to allow, say, basic catalog information to be displayed without some other metadata details.

**Comment by mvahowe** [comment]
Here is feedback regarding REAP and progress.bible, from June 2019 (The information is from Joan at REAP, reformatted and pruned by me). My proposal for confidentiality settings in SB was largely inspired by this.

# In general (I think)

 ### Unrestricted
Basic information about a language engagement or a product (that it exists, the domains/type of work, and involvement of the reporting organization) is viewable by progress.Bible users and may be shared publicly.

###  Restricted
Basic information about the language engagement or product is viewable by progress.Bible users and may be shared from one organization to another for meetings and planning purposes, but should not be shared publicly without the permission of the named organization, typically using a pseudonym (shared in a new story or prayer item, not in a list of actual works)

### Confidential
Basic information will not be shown in the progress.Bible system except to indicate that there is Work in Progress. Information is primarily used for counts of languages in statistics, and for directing accepted inquiries back to the engaged organization to grant specific permission.
 
# REAP
In REAP, which is the SIL system that feeds product data into progress.Bible, we have five levels. REAP is only accessible to people in approved identity providers associated with specific organizations that are known to the REAP administration team. It is not open access, or “sign up for access”.

### Public
All details of the product may be shared publicly.

### Strategic Partners
("probably not of great help to others")

This is a somewhat fuzzily defined set of organizations that SIL partners with globally [details omitted]

### SIL only
This data is visible to anyone in SIL, but is only shared at the discretion of the SIL organizational unit originating it, with specific purposes defined. The sharing of progress.Bible is one such case, and the data is treated as Restricted in progress.Bible.

### Two "Within SIL" categories, out of scope for SB

# Sensitivity settings
In REAP there are up to three “sensitivity settings” recorded for any given item:

### Metadata sensitivity
How much can the details about the work be shared

### Presentation file sensitivity
Who would be granted access to a publishable form (pdf, jpeg, mpeg, and the like) of the work itself.

### Source file sensitivity
Who would be granted access the source files used to produce the publishable form (XML files, InDesign files, other forms of tagged content, high fidelity audio, etc.)

The Source file sensitivity is very often quite restricted, but not always. It depends on the purpose of the work. [Details omitted]

**Comment by jag3773** [comment]
Agreed that we'll run this by other interested parties to ensure we are all on the same page.  In particular, the three fold Unrestricted, Restricted, and Confidential enum.

**Comment by jag3773** [comment]
Add a note to 0.2.0 requesting feedback on this for 0.3.0.

**Comment by jag3773** [comment]
@jonathanrobie Please check with existing stakeholders to see if this will meet their needs.

**Comment by jonathanrobie** [comment]
Joan Spanne of progress.Bible wrote this to me and a few others:

> Hi All,
 
As Mark Howe noted in the GitHub comment stream, the definition used SIL’s REAP model for security metadata and access, and also ProgressBible’s model for security metadata and access.
Those definitions are given, to the degree that they are relevant as models.
I do not think probing either REAP or ProgressBible will provide much more input, unless the questions are quite targeted.
Definitions need to be application specific, and then crosswalked to the degree possible to other environments.
I don’t think the ScriptureBurrito definitions should be directly linked to or driven by REAP’s definitions. The coupling must remain looser than that.
 
-Joan

**Comment by jtauber** [comment]
What is the next action here?

**Comment by jonathanrobie** [comment]
Can we just remove the confidentiality field?

@FoolRunning I assume this is is not present in Paratext translation projects?

**Comment by rdb** [comment]
It is present.

**Comment by jonathanrobie** [comment]
@rdb but there is no clear definition for what its allowed or what it means?

**Comment by jonathanrobie** [comment]
In Paratext Help, we have the following advice for confidential projects:

**For a new project:**

 When you register your project (How do I register a project in Paratext?), select Confidential for the "Visibility" setting. "Confidential" indicates that the project should not be publicly known and that the identity of project members needs to be kept confidential.

**Comment by rdb** [comment]
There is no specification, only advice and suggestions.

Certainly there is language that indicates that the information (it's not specified which information, but in practice it can certainly include metadata such as country and language, or at least the combination of several of these fields) can not become public, especially because there may be security concerns.

**Comment by jag3773** [comment]
0.3.0, let's set this to a boolean and document it like this:

>"Confidential" indicates that the project should not be publicly known and that the identity of project members needs to be kept confidential.

**Comment by rdb** [comment]
That wording is strange for SB since SB (to my knowledge) does not store information about the identity of project members.

**Comment by jonathanrobie** [comment]
True, but I'm thinking about the Tibetan translation on DBL that once had
version history, identifying project members, as remarks in files.  Even
though the Burrito does not know that the remarks contain names of project
members, a human being would.  This is basically a statement of intent to
human beings working with this kind of data.

**Comment by jtauber** [comment]
Implemented in #255
