### ISSUE TITLE
translationType and audience consistency

### ISSUE THREAD

**Issue by rdb** [bible-technology/scripture-burrito#92]
The possible values for `<translationType>` are:
* `First`
* `New`
* `Revision`
* `Study / Help Material`

And for `<audience>`:
* `Basic`
* `Common`
* `Common - Literary`
* `Literary`
* `Liturgical`
* `Children`

This is inconsistent with most other fields, which use semantic camelCase strings instead of an English string with spaces and punctuation.  I believe this was essentially grandfathered in from existing DBL/Registry conventions, but I posit that we should value producing a consistent specification that eases adoption over inheriting a particular wart of one implementation, especially in cases where mapping to a new convention is trivial.

**Comment by mvahowe** [comment]
Yes, we should make this consistent, and also maybe ask if this is the most useful enum. (It looks to me like that something that grew to meet the next new use case, rather than a thought-through set of categories.)

**Comment by jag3773** [comment]
Consider adding a sliding scale of form centric vs meaning centric.

**Comment by jag3773** [comment]
Consider a tagging scheme as well.

**Comment by mvahowe** [comment]
Can we close this in favor of #104? That issue already links to this one.
