### ISSUE TITLE
Document Semantic Versioning Meaning

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#97]
We've agreed to follow semantic versioning for the `version` field (and hence [removed minVersion](https://github.com/bible-technology/scripture-burrito/commit/2355a34b51976e491cd0a7abf9b5f5b73562a84e)) but we need to define how we are interpreting semantic versioning.

In particular, we need to describe when it's allowed to add new fields.

**Comment by jag3773** [comment]
Duplicate of #106

**Comment by jonathanrobie** [comment]
I propose that we allow new fields to be added within a major version as long as they do not change the semantics of existing fields.  I propose the following test:  if an existing client that uses major version N and was written for a version lower than N.X can continue to work with N.X without modification, then we stick with N as the major version.

If the version introduces breaking changes, we bump the major version.  We avoid doing that unless we have to.

**Comment by jag3773** [comment]
I believe all this has been documented appropriately at https://docs.burrito.bible/en/v0.2.0-beta/schema_docs/design.html#versioning via issue #106 , closing this for now.
