### ISSUE TITLE
Update to JSON Schema 2019-09 

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#98]
I think this is a low impact change, but since 2019-09 is out seems like we should update our schema to match before our 0.2.0 release.  See https://json-schema.org/draft/2019-09/release-notes.html for upgrade notes.

**Comment by rdb** [comment]
I'm not opposed in principle, but it was only just released, so it may be best to wait until [jsonschema](https://pypi.org/project/jsonschema/) and [ajv](https://ajv.js.org/) support the new version.

**Comment by rdb** [comment]
For the record, I skimmed the release notes and it may be that the only change we'd need to make is rename "definitions" to "$defs".
