### ISSUE TITLE
Recreate XML examples in JSON

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#99]
* [x] glossed_text_story.xml 
* [x]	parascriptural_word_alignment.xml
* [x]	peripheral_versification.xml
* [x]	scripture_audio.xml
* [x]	scripture_braille.xml
* [x]	scripture_print_pdf.xml
* [x]	scripture_sign_language.xml
* [x]	scripture_text.xml
* [x]	scripture_x.xml

**Comment by rdb** [comment]
scripture_text.xml is already there in the form of scriptureText.json

**Comment by mvahowe** [comment]
PR #169 adds an audio example, generated from DBL metadata.

**Comment by mvahowe** [comment]
Added print example and refreshed text one re pr #169

**Comment by mvahowe** [comment]
Added SL example re pr #169

**Comment by mvahowe** [comment]
Added remaining non-x flavors in pr #173

**Comment by mvahowe** [comment]
And, finally, the xScripture example in pr #173
